def getContent(vKey):
    if vKey == '0_0P':
        vResult = '<title>HTKB Home Page</title>'
        vResult += '<h2>'
        vResult += '    Welcome to the House That Kamurai Built!'
        vResult += '</h2>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    The House That Kamurai Built is an '
        vResult += '    entertainment company with the primary '
        vResult += '    focus of increasing awesome by stimulating '
        vResult += '    intelligent conversation and entertainment '
        vResult += '    via discussion and game design. <br>'
        vResult += '    Increase the Awesome with us!<br>'
        vResult += '</p>'
    elif vKey == '0_1P':
        vResult = '<title>About Us</title>'
        vResult += '<h2>'
        vResult += '    About Us'
        vResult += '</h2>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    We are working to build this into a better place.</br>'
        vResult += '    If you found this, then you must be at least (Awesome/2).</br>'
        vResult += '    Stay tuned, right now it\'s all about laying foundation for the future.</br>'
        vResult += '</p>'
    elif vKey == '0_2P':
        vResult = '<title>Media</title>'
        vResult += '<h2>'
        vResult += '    Media'
        vResult += '</h2>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    You can find us at all these different places:</br>'
        vResult += '    <br/>'
        vResult += '    <br/>'
        vResult += '        #WeAreMovieClub:'
        vResult += '    <br/>'
        vResult += '    <br/>'
        vResult += '        <a href=\'http://www.youtube.com/WeAreMovieClub\'>Youtube.com/WeAreMovieClub:  A place for movie discussion.</a></br>'
        vResult += '        <a href=\'http://WeAreMovieClub.tumblr.com\'>WeAreMovieClub.tumblr.com: We have a tumblr!</a></br>'
        vResult += '        <a href=\'http://www.twitter.com/WeAreMovieClub\'>@WeAreMovieClub on Twitter: Let us know about your movie thoughts.</a></br>'
        vResult += '        <a href=\'http://www.facebook.com/WeAreMovieClub\'>facebook.com/WeAreMovieClub: Talk about movie with us.</a></br>'
        vResult += '    <br/>'
        vResult += '    <br/>'
        vResult += '        HTKB Productions'
        vResult += '    <br/>'
        vResult += '    <br/>'
        vResult += '        <a href=\'http://www.youtube.com/GamingDivision528\'>Gaming Division:  A Youtube Channel for game stuff.</a></br>'
        vResult += '        <a href=\'http://www.youtube.com/JamOnToast528\'>Jam On Toast:  A Youtube Channel for media stuff.</a></br>'
        vResult += '        <a href=\'http://www.ustream.tv/HTKB\'>UStream:  Streams show up here too.</a></br>'
        vResult += '        <a href=\'http://www.firetalk.com/HTKB\'>FireTalk:  Streams show up here too.</a></br>'
        vResult += '        <a href=\'http://www.younow.com/HTKB\'>YouNow:  Streams show up here too.</a></br>'
        vResult += '        <a href=\'http://www.soundcloud.com/HTKB\'>Sound Cloud:  Listen to our podcasts.</a></br>'
        vResult += '        <a href=\'http://HTKB.podbean.com/\'>Pod Bean:  Listen to our podcasts.</a></br>'
        vResult += '        <a href=\'http://www.youtube.com/HTKB\'>Youtube:  Thoughts and life discussions.</a></br>'
        vResult += '        <a href=\'http://www.patreon.com/HTKBProductions\'>Patreon:  You can help make our dreams reality.</a></br>'
        vResult += '        <a href=\'http://www.facebook.com/HouseThatKamuraiBuilt\'>Facebook: Talk about movie with us.</a></br>'
        vResult += '        <a href=\'http://HouseThatKamuraiBuilt.tumblr.com\'>HouseThatKamuraiBuilt.tumblr.com: We have a tumblr!</a></br>'
        vResult += '        <a href=\'http://myspace.com/HouseThatKamuraiBuilt\'>Myspace: Wow, there\'s even a MySpace!</a></br>'
        vResult += '    <br/>'
        vResult += '        Here are some of our member\'s pages:</br>'
        vResult += '    <br/>'
        vResult += '            Kamurai:'
        vResult += '    <br/>'
        vResult += '    <br/>'
        vResult += '        <a href=\'http://twitter.com/#!/Kamurai25\'>Kamurai\'s Twitter.</a></br>'
        vResult += '        <a href=\'http://Instagram.com/Kamurai25\'>Kamurai\'s Instagram.</a></br>'
        vResult += '        <a href=\'./.\'>Kamurai\'s Snapchat: Kamurai</a></br>'
        vResult += '        <a href=\'http://www.facebook.com/cris.kamurai\'>Kamurai\'s Facebook.</a></br>'
        vResult += '        <a href=\'https://www.gplus.com/Members/Cris-Kamurai\'>Kamurai\'s Google Plus.</a></br>'
        vResult += '        <a href=\'http://www.yoyogames.com/users/Kamurai\'>Kamurai\'s YoYo Games page:  See some of the games he\'s posted.</a></br>'
        vResult += '</p>'
    elif vKey == '0_3P':
        vResult = '<title>Minecraft!</title>'
        vResult += '<h2>'
        vResult += '    Minecraft!'
        vResult += '</h2>'
        vResult += '    <p id=\'idCenterContent\'>'
        vResult += '        If you would like to play Minecraft with us, we have several different servers:</br>'
        vResult += '        Mo Creatures Server: (1.7.10) htkb.dyndns.org:25565</br>'
        vResult += '        Creative Server:     (1.7.10) htkb.dyndns.org:25567</br>'
        vResult += '            This is a list of mods that we are using on the server, compatible with 1.7.10.</br>'
        vResult += '            <a href=\'./Downloads/Minecraft/forge-1.7.10-10.13.3.1401-1710ls-installer.jar\'>Forge 1.7.10</a></br>'
        vResult += '            <a href=\'./Downloads/Minecraft/DrZharks MoCreatures Mod v6.3.1.zip\'>Dr Zhark\'s Mo Creatures</a></br>'
        vResult += '            <a href=\'./Downloads/Minecraft/CustomMobSpawner 3.3.0.zip\'>Custom Mob Spawner</a></br>'
        vResult += '            <a href=\'./Downloads/Minecraft/[1.7.10]Gender-1.0.2.jar\'>iPixeli\'s Gender Mod</a></br>'
        vResult += '            <a href=\'./Downloads/Minecraft/BspkrsCore-1.7.10.jar\'>Bspkrs Core</a></br>'
        vResult += '            <a href=\'./Downloads/Minecraft/[1.7.10]Treecapitator-universal-2.0.4.jar\'>Tree Capitator</a></br>'
        vResult += '            <a href=\'./Downloads/Minecraft/MoarFood-5.8.0.jar\'>Moar Food</a></br>'
        vResult += '            <a href=\'./Downloads/Minecraft/MoarOres-2.4.5.jar\'>Moar Ores</a></br>'
        vResult += '            <a href=\'./Downloads/Minecraft/BiblioCraft[v1.10.4][MC1.7.10].jar\'>Biblio Craft</a></br>'
        vResult += '            <a href=\'./Downloads/Minecraft/Fossils_Archeology_Revival-1.7.10_Build-6.4b.jar\'>Fossils and Archaeology</a></br>'
        vResult += '            <a href=\'./Downloads/Minecraft/Reis-Minimap-Mod-1.7.10.jar\'>Rei\'s Minimap</a></br>'
        vResult += '            <a href=\'./Downloads/Minecraft/Xaeros_Minimap_1.10.8_Forge_1.7.10.jar\'>Xaero\'s Minimap</a></br>'
        vResult += '        Vanilla Server:      htkb.dyndns.org:25566</br>'
        vResult += '        Here is a skin template to make custom skins:</br>'
        vResult += '        <a href=\'./Downloads/Minecraft/skin_template.png\'>Steve skin template</a></br>'
        vResult += '        <br/>'
        vResult += '        <br/>'
        vResult += '        For first time setups, please follow these steps to make your client compatible with the server:</br>'
        vResult += '             0) If you don\'t have Minecraft, go to Minecraft.net and download the latest version of the launcher.</br>'
        vResult += '             1) From the launcher create a new profile and change its version to the relevant version (e.g. 1.7.10).</br>'
        vResult += '             2) Save the Profile, select the new profile and click play.</br>'
        vResult += '             3) Exit the program.</br>'
        vResult += '             4) Install Forge.  If it is not automatically selected, then browse to your .minecraft folder.</br>'
        vResult += '                Windows: It is in a hidden folder: c:\Users\*Username*\Appdata\Roaming\.minecraft</br>'
        vResult += '                Mac: \'Go to\' ~/Library/Application Support/minecraft</br>'
        vResult += '             5) If you are managing multiple non-compatible mods, then you man have to make folders like:</br>'
        vResult += '                \'..\Roaming\MoCreatures\'</br>'
        vResult += '             6) If your folder doesn\'t have a /Mods folder, create one. Place the files from the mod list into the /mods folder.</br>'
        vResult += '                Even if it works, don\'t put two minimap mods in the same folder.</br>'
        vResult += '             7) Open the Minecraft Launcher, edit your version (e.g. 1.7.10) profile to use the forge version of the same.</br>'
        vResult += '             8) If you are using a different folder, then remember to change the Game Directory in the profile.</br>'
        vResult += '             9) Save the Profile, select the new profile and click play.</br>'
        vResult += '            10) You should see the mods listed on the side of the Minecraft window.</br>'
        vResult += '            11) Go to multiplayer and click add server.</br>'
        vResult += '            12) Name the server something distinct and put \'htkb.dyndns.org:2556x\' in the address bar where \'x\' is the relevant port.</br>'
        vResult += '            13) Save the server entry.  You should see a connection to the server.  Double click to join.</br>'
        vResult += '    </p>'
    elif vKey == '1_0P':
        vResult  = '<title>Web Programming</title>'
        vResult += '<h1>'
        vResult += '    Web Programming'
        vResult += '</h1>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    This section is dedicated to Web based programming.'
        vResult += '</p>'
    elif vKey == '1_1P':
        vResult  = '<title>HTML Programming</title>'
        vResult += '<h1>'
        vResult += '    HTML Programming'
        vResult += '</h1>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    This section is dedicated to HTML based programming.'
        vResult += '</p>'
    elif vKey == '1_2_0P':
        vResult  = '<title>Database Programming</title>'
        vResult += '<h1>'
        vResult += '    Database Programming'
        vResult += '</h1>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    This section is dedicated to database based programming.'
        vResult += '</p>'
    elif vKey == '1_4_0P':
        vResult  = '<title>Java Programming</title>'
        vResult += '<h1>'
        vResult += '    Java Programming'
        vResult += '</h1>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    This section is dedicated to Java based programming.'
        vResult += '</p>'
    elif vKey == '1_5_0P':
        vResult = '<title>ASP.NET Programming</title>'
        vResult += '<h1>'
        vResult += '    ASP.NET Programming'
        vResult += '</h1>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    This section is dedicated to ASP.NET based programming.'
        vResult += '</p>'
    elif vKey == '1_6_0P':
        vResult  = '<title>Database Programming</title>'
        vResult += '<h1>'
        vResult += '    Database Programming'
        vResult += '</h1>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    This section is dedicated to database based programming.'
        vResult += '</p>'
    elif vKey == '1_6_1P':
        vResult = '<title>Oracle Programming</title>'
        vResult += '<h1>'
        vResult += '    Oracle Programming'
        vResult += '</h1>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    This section is dedicated to Oracle programming.'
        vResult += '</p>'
    elif vKey == '1_6_2P':
        vResult = '<title>Derby Programming</title>'
        vResult += '<h1>'
        vResult += '    Derby Programming'
        vResult += '</h1>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    This section is dedicated to Derby programming.'
        vResult += '</p>'
    elif vKey == '1_6_3P':
        vResult  = '<title>MySQL Programming</title>'
        vResult += '<h1>'
        vResult += '    MySQL Programming'
        vResult += '</h1>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    This section is dedicated to MySQL programming.'
        vResult += '</p>'
    elif vKey == '1_6_4P':
        vResult  = '<title>SQL Server Programming</title>'
        vResult += '<h1>'
        vResult += '    SQL Server Programming'
        vResult += '</h1>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    This section is dedicated to SQL Server programming.'
        vResult += '</p>'
    elif vKey == '1_6_5P':
        vResult  = '<title>Postgres Programming</title>'
        vResult += '<h1>'
        vResult += '    Postgres Programming'
        vResult += '</h1>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    This section is dedicated to Postgres programming.'
        vResult += '</p>'
    elif vKey == '2_0P':
        vResult  = '<title>'
        vResult += '    Private Projects'
        vResult += '</title>'
        vResult += '<h1>'
        vResult += '    Private Projects'
        vResult += '</h1>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    This section is dedicated to HTKB projects.'
        vResult += '</p>'
    elif vKey == '2_2P':
        vResult  = '<title>'
        vResult += '    Assault CCG'
        vResult += '</title>'
        vResult += '<h1>'
        vResult += '    Assault CCG'
        vResult += '</h1>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    This section is dedicated CCG project \'Assault\'.'
        vResult += '</p>'
    elif vKey == '2_3P':
        vResult = '<title>'
        vResult += '    Mars Projects'
        vResult += '</title>'
        vResult += '<h1>'
        vResult += '    Mars Projects'
        vResult += '</h1>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    This section is dedicated to the Mars centered project \'Opposition\'.'
        vResult += '</p>'
    elif vKey == '2_7P':
        vResult = '<title>'
        vResult += '    Truth'
        vResult += '</title>                                '
        vResult += '<h1>'
        vResult += '    Truth'
        vResult += '</h1>                '
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    This section is dedicated to the MMO RTS project \'Truth\'.  Explore the galaxy, smuggle goods, steal from your friends and battle your adversaries.'
        vResult += '</p>'
    elif vKey == '2_8P':
        vResult = '<title>'
        vResult += '    Kingdoms'
        vResult += '</title>'
        vResult += '<h1>'
        vResult += '   Kingdoms'
        vResult += '</h1>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    This section is dedicated to the digital board game project \'Kingdoms\'.  Explore the world\'s Kingdoms, get rich, get strong and conquer.'
        vResult += '</p>'
    elif vKey == '2_9P':
        vResult = '<title>'
        vResult += '    Terminal World'
        vResult += '</title>'
        vResult += '<h1>'
        vResult += '    Terminal World'
        vResult += '</h1>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    This section is dedicated to the simulation MMO centered project \'Terminal World\'.  This is a virtual environment where a zombie outbreak is about to happen.  Can you beat the zombies?  Can you survive?'
        vResult += '</p>'
    elif vKey == '2_10P':
        vResult = '<title>'
        vResult += '    Monster Office Workplace'
        vResult += '</title>'
        vResult += '<h1>'
        vResult += '    Monster Office Workplace'
        vResult += '</h1>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    This section is dedicated to the card and board game project \'Monster Office Workplace\'.  These monsters mean serious business.  Can you earn the most credit and smooze your way into a promotion?'
        vResult += '</p>'
    elif vKey == '2_11P':
        vResult = '<title>'
        vResult += '    Battle Princesses'
        vResult += '</title>'
        vResult += '<h1>'
        vResult += '    Battle Princesses'
        vResult += '</h1>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    This section is dedicated to the card game project \'Battle Princesses\'.  Ever wanted to see your favorite princess battle for the kingdom?  These princess aren\'t your helpless maidens, but valiant warriors themselves.'
        vResult += '</p>'
    elif vKey == '2_12P':
        vResult = '<title>'
        vResult += '    Sacred Offerings'
        vResult += '</title>'
        vResult += '<h1>'
        vResult += '    Sacred Offerings'
        vResult += '</h1>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    This section is dedicated to the board game project \'Sacred Offerings\'.  Being a god is hard, you have to eat, but don\'t want to fall out favor with the people more than the other deities.  Draw people to worship you, but be discerning about who is sacrificed.'
        vResult += '</p>'
    elif vKey == '2_13P':
        vResult = '<title>'
        vResult += '    The Way'
        vResult += '</title>'
        vResult += '<h1>'
        vResult += '    The Way'
        vResult += '</h1>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    This section is dedicated to the card game project \'The Way\'.  You seek to find enlightment by contemplating the elements.  Escape the binds of the world and the board to reach enlightment and win.'
        vResult += '</p>'
    elif vKey == '2_14P':
        vResult = '<title>'
        vResult += '    Conspiratorium'
        vResult += '</title>'
        vResult += '<h1>'
        vResult += '    Conspiratorium'
        vResult += '</h1>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    This section is dedicated to the board game project \'Conspiratorium\'.  A game of assassins and CIA, you must remember who is friend and who is not.'
        vResult += '</p>'
    elif vKey == '2_15P':
        vResult = '<title>'
        vResult += '    Conversion'
        vResult += '</title>'
        vResult += '<h1>'
        vResult += '    Conversion'
        vResult += '</h1>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    This section is dedicated to the board game project \'Conversion\'.  Compete on the elemental market by processing elements and becoming the elemental kingpin.'
        vResult += '</p>'
    elif vKey == '2_1_0P':
        vResult = '<title>'
        vResult += '    Gynowars'
        vResult += '</title>'
        vResult += '<h1>'
        vResult += '    Gynowars'
        vResult += '</h1>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    This section is dedicated to projects centered in the Gynowars universe.'
        vResult += '</p>'
    elif vKey == '2_1_1P':
        vResult  = '<title>'
        vResult += '    Gynowars RPG'
        vResult += '</title>'
        vResult += '<h1>'
        vResult += '    Gynowars RPG'
        vResult += '</h1>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    The Gynowars RPG is a \'pokemon-like\' tactical RPG.  The protagonist uses creatures to fight battles against other creatures to progress through the storyline.'
        vResult += '</p>'
    elif vKey == '2_1_2P':
        vResult  = '<title>'
        vResult += '    Gynowars: Battle Arena CCG'
        vResult += '</title>'
        vResult += '<h1>'
        vResult += '    Gynowars: Battle Arena CCG'
        vResult += '</h1>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    Gynowars: Battle Arena is a CCG that pits teams of creatures against each other in an arena-like environment.  There are several scenarios to run, to include:</br>\'Death Match\', \'Ring the Bell\', and \'Head Hunt\'.                                        '
        vResult += '</p>'
    elif vKey == '2_1_3P':
        vResult  = '<title>'
        vResult += '    Gynowars: Crash Ball'
        vResult += '</title>'
        vResult += '<h1>'
        vResult += '    Gynowars: Crash Ball'
        vResult += '</h1>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    Gynowars: Crash Ball is a turn based strategy board game.  Basically it\'s gridiron with Gynos.'
        vResult += '</p>'
    elif vKey == '2_4_0P':
        vResult  = '<title>'
        vResult += '    Renley'
        vResult += '</title>'
        vResult += '<h1>'
        vResult += '    Renley'
        vResult += '</h1>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    This section is dedicated to projects centered in the Renley universe.'
        vResult += '</p>'
    elif vKey == '2_4_1P':
        vResult  = '<title>'
        vResult += '    Warring Nations'
        vResult += '</title>'
        vResult += '<h1>'
        vResult += '    Warring Nations'
        vResult += '</h1>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    Warring Nations is a Tactical RPG involving squad based battles. Characters advance classes based on their weapon proficiencies and/or currently equipped weapons.'
        vResult += '</p>'
    elif vKey == '2_4_2P':
        vResult = '<title>'
        vResult += '    Psychodom: The One Empire'
        vResult += '</title>'
        vResult += '<h1>'
        vResult += '    Psychodom: The One Empire'
        vResult += '</h1>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    Psychodom: The One Empire is a 3rd person perspective Adventure / RPG.  The protagonist is tasked with investigating various situations leading to a conspiracy about who is really ruling the continent.'
        vResult += '</p>'
    elif vKey == '2_5_0P':
        vResult = '<title>'
        vResult += '    Antarrea Projects'
        vResult += '</title>'
        vResult += '<h2>'
        vResult += '    Antarrea Projects'
        vResult += '</h2>'
        vResult += '<h3>'
        vResult += '    <p id=\'idCenterContent\'>'
        vResult += '        Global:'
        vResult += '    </p>'
        vResult += '</h3>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    Here are projects based in the Antarrea universe:</br>'
        vResult += '    </br>'
        vResult += '    Team Tactical: Crash Ball:               Tactical board game centered on a battle version of football.</br>'
        vResult += '    Wars of Antarrea:                        Table-top game where two or more armies battle for supremacy.</br>'
        vResult += '    Revolutions: Invading Nations:           Tactical RPG, 1st story arc.</br>'
        vResult += '    Revolutions: Rebellion Against the Fist: Tactical RPG, 2nd story arc.</br>'
        vResult += '    Revolutions: Return to Arms:             Tactical RPG, 3rd story arc.</br>'
        vResult += '    Revoultions: Post Wars:                  Tactical RPG, 4th story arc.</br>'
        vResult += '    <h3>'
        vResult += '        <p id=\'idCenterContent\'>'
        vResult += '            Grendol:'
        vResult += '        </p>'
        vResult += '    </h3>'
        vResult += '    <p id=\'idCenterContent\'>'
        vResult += '         Here are projects based in the Grendol universe:</br>'
        vResult += '        </br>'
        vResult += '        Grendol: Land of the Orcish Empire: Age of Magic: CCG.</br>'
        vResult += '        Grendol: Coliseum: Arena:                         CCG.</br>'
        vResult += '    </p>'
        vResult += '    <h3>'
        vResult += '        <p id=\'idCenterContent\'>'
        vResult += '            Utopia:'
        vResult += '        </p>'
        vResult += '    </h3>'
        vResult += '    <p id=\'idCenterContent\'>'
        vResult += '        Here are projects based in the Utopia universe:</br>'
        vResult += '       </br>'
        vResult += '        Avia: Elemental Angels: Adventure game with RPG elements.</br>'
        vResult += '    </p>'
        vResult += '    <h3>'
        vResult += '        <p id=\'idCenterContent\'>'
        vResult += '            Elvia:'
        vResult += '        </p>'
        vResult += '    </h3>'
        vResult += '    <p id=\'idCenterContent\'>'
        vResult += '        Here are projects based in the Elvia universe:</br>'
        vResult += '        </br>'
        vResult += '        Nine Card: Tactical card game.</br>'
        vResult += '    </p>'
        vResult += '</p>'
    elif vKey == '2_5_1':
        vResult = '<title>'
        vResult += '    Global Antarrea'
        vResult += '</title>'
        vResult += '<h2>'
        vResult += '    Global Antarrea'
        vResult += '</h2>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    Here are projects based in the Antarrea universe:</br>'
        vResult += '    </br>'
        vResult += '    Team Tactical: Crash Ball:               Tactical board game centered on a battle version of football.</br>'
        vResult += '    Wars of Antarrea:                        Table-top game where two or more armies battle for supremacy.</br>'
        vResult += '    Revolutions: Invading Nations:           Tactical RPG, 1st story arc.</br>'
        vResult += '    Revolutions: Rebellion Against the Fist: Tactical RPG, 2nd story arc.</br>'
        vResult += '    Revolutions: Return to Arms:             Tactical RPG, 3rd story arc.</br>'
        vResult += '    Revoultions: Post Wars:                  Tactical RPG, 4th story arc.</br>'
        vResult += '</p>'
    elif vKey == '2_5_1_1P':
        vResult = '<title>'
        vResult += '    Team Tactical: Crash Ball'
        vResult += '</title>'
        vResult += '<h2>'
        vResult += '    Team Tactical: Crash Ball'
        vResult += '</h2>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    Team Tactical: Crash Ball is a tactical board game centered on a battle version of football.'
        vResult += '    </br>'
        vResult += '</p>'
    elif vKey == '2_5_1_2P':
        vResult = '<title>'
        vResult += '    Wars of Antarrea'
        vResult += '</title>'
        vResult += '<h2>'
        vResult += '    Wars of Antarrea'
        vResult += '</h2>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    Wars of Antarrea is a table-top game where two or more armies battle for supremacy.</br>'
        vResult += '</p>'
    elif vKey == '2_5_1_3P':
        vResult = '<title>'
        vResult += '    Revolutions: Invading Nations'
        vResult += '</title>'
        vResult += '<h2>'
        vResult += '    Revolutions: Invading Nations'
        vResult += '</h2>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    Revolutions is a Tactical RPG with Invading Nations as its 1st story arc.</br>'
        vResult += '</p>'
    elif vKey == '2_5_1_4P':
        vResult = '<title>'
        vResult += '    Revolutions: Rebellion Against the Fist'
        vResult += '</title>'
        vResult += '<h2>'
        vResult += '    Revolutions: Rebellion Against the Fist'
        vResult += '</h2>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    Revolutions is a Tactical RPG with Rebellion Against the Fist as its 2nd story arc.</br>'
        vResult += '</p>'
    elif vKey == '2_5_1_5P':
        vResult = '<title>'
        vResult += '    Revolutions: Return to Arms'
        vResult += '</title>'
        vResult += '<h2>'
        vResult += '    Revolutions: Return to Arms'
        vResult += '</h2>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    Revolutions is a Tactical RPG with Return to Arms as its 3rd story arc.</br>'
        vResult += '</p>'
    elif vKey == '2_5_1_6P':
        vResult = '<title>'
        vResult += '    Revolutions: Post Wars'
        vResult += '</title>'
        vResult += '<h2>'
        vResult += '    Revolutions: Post Wars'
        vResult += '</h2>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    Revolutions is a Tactical RPG with Post Wars as its 4th story arc.</br>'
        vResult += '</p>'
    elif vKey == '2_5_2_0P':
        vResult = '<title>'
        vResult += '    Grendol'
        vResult += '</title>'
        vResult += '<h2>'
        vResult += '    Grendol'
        vResult += '</h2>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    Here are projects based in the Grendol Empire:</br>'
        vResult += '    </br>'
        vResult += '    Land of the Orcish Empire: Age of Magic: a CCG based on the different factions that comprise the Grendol Empire.</br>'
        vResult += '    Coliseum: Arena: a CCG representing the gladitorial arenas of Grendol.</br>'
        vResult += '</p>'
    elif vKey == '2_5_2_1P':
        vResult = '<title>'
        vResult += '    Land of the Orcish Empire: Age of Magic'
        vResult += '</title>'
        vResult += '<h2>'
        vResult += '    Land of the Orcish Empire: Age of Magic'
        vResult += '</h2>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    Land of the Orcish Empire: Age of Magic: is a CCG based on the different factions that '
        vResult += '    comprise the Grendol Empire.'
        vResult += '</p>'
    elif vKey == '2_5_2_2P':
        vResult = '<title>'
        vResult += '    Coliseum: Arena'
        vResult += '</title>'
        vResult += '<h2>'
        vResult += '    Coliseum: Arena'
        vResult += '</h2>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    Coliseum: Arena is a CCG representing the gladitorial arenas of Grendol.'
        vResult += '</p>'
    elif vKey == '2_5_3_0P':
        vResult = '<title>'
        vResult += '    Utopia'
        vResult += '</title>'
        vResult += '<h2>'
        vResult += '    Utopia'
        vResult += '</h2>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    Here are projects based in the Utopia Nation:</br>'
        vResult += '    </br>'
        vResult += '    Elemental Angels: An adventure game with RPG elements based in the Avia Nation.</br>'
        vResult += '</p>'
    elif vKey == '2_5_3_1P':
        vResult = '<title>'
        vResult += '    Elemental Angels'
        vResult += '</title>'
        vResult += '<h2>'
        vResult += '    Elemental Angels'
        vResult += '</h2>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    Elemental Angels: Adventure game with RPG elements based in the Avia Nation.</br>'
        vResult += '</p>'
    elif vKey == '2_5_4_0P':
        vResult = '<title>'
        vResult += '    Elvia'
        vResult += '</title>'
        vResult += '<h2>'
        vResult += '    Elvia'
        vResult += '</h2>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    Here are projects based in the Elvia Empire:</br>'
        vResult += '    </br>'
        vResult += '    Nine Card: a Tactical card game played through the Elvia Empire.</br>'
        vResult += '</p>'
    elif vKey == '2_5_4_1P':
        vResult = '<title>'
        vResult += '    Nine Card'
        vResult += '</title>'
        vResult += '<h2>'
        vResult += '    Nine Card'
        vResult += '</h2>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    Nine Card is a Tactical card game played through the Elvia Empire.</br>'
        vResult += '</p>'
    elif vKey == '2_6_0P':
        vResult = '<title>'
        vResult += '    Editations'
        vResult += '</title>'
        vResult += '<h1>'
        vResult += '    Editations'
        vResult += '</h1>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    This section is dedicated to projects that edit universes outside of HTKB.'
        vResult += '</p>'
    elif vKey == '2_6_1P':
        vResult = '<title>'
        vResult += '    Magic: The Tactical'
        vResult += '</title>'
        vResult += '<h1>'
        vResult += '    Magic: The Tactical'
        vResult += '</h1>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    This section is dedicated to a modified game based on the \'Magic: The Gathering\' CCG.'
        vResult += '</p>'
    elif vKey == '2_6_2_0P':
        vResult = '<title>'
        vResult += '    Warhammer 40K'
        vResult += '</title>'
        vResult += '<h1>'
        vResult += '    Warhammer 40K'
        vResult += '</h1>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    This section is dedicated to projects that edit the Warhammer 40K universe.'
        vResult += '</p>'
    elif vKey == '2_6_2_1P':
        vResult = '<title>'
        vResult += '    Mission!'
        vResult += '</title>'
        vResult += '<h1>'
        vResult += '    Mission!'
        vResult += '</h1>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    This section is dedicated to an adventure RPG project in the Warhammer 40K universe.'
        vResult += '</p>'
    elif vKey == '2_6_2_2_0P':
        vResult = '<title>'
        vResult += '    HTKB Armies'
        vResult += '</title>'
        vResult += '<h1>'
        vResult += '    HTKB Armies'
        vResult += '</h1>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    This section is dedicated to HTKB designed armies based on the Warhammer 40K universe.'
        vResult += '</p>'
    elif vKey == '2_6_2_2_1P':
        vResult = '<title>'
        vResult += '    Ad Infinitum'
        vResult += '</title>'
        vResult += '<h1>'
        vResult += '    Ad Infinitum'
        vResult += '</h1>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    Ad Infinitum is a collective of A.I. constructs.  Little is known about these constructs '
        vResult += '    as they are not known to negotiate.  While some technology has been recovered, it is rare '
        vResult += '    to find anything viable after battles.'
        vResult += '</p>'
    elif vKey == '2_6_2_2_2P':
        vResult = '<title>'
        vResult += '    Avia'
        vResult += '</title>'
        vResult += '<h1>'
        vResult += '    Avia'
        vResult += '</h1>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    The Avia are a humanoid xenos that are naturally equipped with wings.  They can are the very least '
        vResult += '    glide for short times without technological assistance.'
        vResult += '</p>'
    elif vKey == '2_6_2_2_3P':
        vResult = '<title>'
        vResult += '    De Luna'
        vResult += '</title>'
        vResult += '<h1>'
        vResult += '    De Luna'
        vResult += '</h1>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    De Luna is a designation for squads of walker vehicles that tend to ambush their targets.  '
        vResult += '    While De Luna are automated vehicles, wreckage has determine that there are seats for '
        vResult += '    pilots.  Theories range from A.I. control to remote communication.'
        vResult += '</p>'
    elif vKey == '2_6_2_2_4P':
        vResult = '<title>'
        vResult += '    Eve'
        vResult += '</title>'
        vResult += '<h1>'
        vResult += '    Eve'
        vResult += '</h1>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    The Eve are a race of terrifying beast creatures.  '
        vResult += '    These Xenos somewhat resemble large cats.'
        vResult += '</p>'
    elif vKey == '2_6_2_2_5P':
        vResult = '<title>'
        vResult += '    Geo Marines'
        vResult += '</title>'
        vResult += '<h1>'
        vResult += '    Geo Marines'
        vResult += '</h1>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    Geo Marines are a specialized Chapter concentrating equipment speciality.'
        vResult += '</p>'
    elif vKey == '2_6_2_2_6P':
        vResult = '<title>'
        vResult += '    Twin Fists'
        vResult += '</title>'
        vResult += '<h1>'
        vResult += '    Twin Fists'
        vResult += '</h1>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    This lost Chapter spent far too long stranded outside the reach of civilisation.  '
        vResult += '    The Twin Fists specialize in close combat battles.'
        vResult += '</p>'
    elif vKey == '2_6_2_2_7P':
        vResult = '<title>'
        vResult += '    Voboulids'
        vResult += '</title>'
        vResult += '<h1>'
        vResult += '    Voboulids'
        vResult += '</h1>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    Vouboulids are a plant-like group of entities.  Using a hive structure, '
        vResult += '    these Xenos seem to concentrate on populating one area at a time, causing a slow expansion.'
        vResult += '</p>'
    elif vKey == '2_6_2_2_8P':
        vResult = '<title>'
        vResult += '    Fungi'
        vResult += '</title>'
        vResult += '<h1>'
        vResult += '    Fungi'
        vResult += '</h1>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    These Xenos are unidentifiable as anything other than an advanced form of Fungus.  '
        vResult += '    Their appearances range incredible wide, but tend to even resemble familiar forms of fungus.'
        vResult += '</p>'
    elif vKey == '2_6_2_2_9P':
        vResult = '<title>'
        vResult += '    Synergy'
        vResult += '</title>'
        vResult += '<h1>'
        vResult += '    Synergy'
        vResult += '</h1>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    These almost intangible Xenos appear to made of energy itself.  They use technology that appears unstable in nature.'
        vResult += '</p>'
    elif vKey == '2_6_2_2_10P':
        vResult  = '<title>'
        vResult += '    The Dark'
        vResult += '</title>'
        vResult += '<h1>'
        vResult += '    The Dark'
        vResult += '</h1>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    The Dark are a Hive centered Xenos resembling a disturbing cross between snake, bird and insect.'
        vResult += '</p>'
    elif vKey == '2_6_2_2_11P':
        vResult  = '<title>'
        vResult += '    Vivus Mortem'
        vResult += '</title>'
        vResult += '<h1>'
        vResult += '    Vivus Mortem'
        vResult += '</h1>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    Vivus mortem is a category for humans that are encountered and exhibit certain traits.  These possibly once humans '
        vResult += '    have extreme abilities to endure the harshest environment, avoid lighted scenarios whenever possible, and attempt to '
        vResult += '    take human prisoner whenever possible.  Escapees had stated that the Vivus Mortem would feed on them, and upon death '
        vResult += '    and exposed bodies lose their excessive durability and seem to disintegrate rapidly enough to appear to \'turn to ash\'.'
        vResult += '</p>'
    elif vKey == '3_0P':
        vResult  = '<title>'
        vResult += '    Downloadable Projects'
        vResult += '</title>'
        vResult += '<h1>'
        vResult += '    Downloadable Projects'
        vResult += '</h1>'
        vResult += '<p  id=\'idCenterContent\'>'
        vResult += '    This section is dedicated to downloadable projects.'
        vResult += '</p>'
    elif vKey == '3_1P':
        vResult  = '<title>'
        vResult += '    Online Experience Downloads'
        vResult += '</title>'
        vResult += '<h2>'
        vResult += '    Online Experience Downloads'
        vResult += '</h2>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    Here are downloads to play Cube World with us:</br>'
        vResult += '    </br>'
        vResult += '    Cube World:<t><a href=\'http://htkb.dyndns.org/downloadsCubeSetup3.exe\'>Come play Cube World!</a></br>'
        vResult += '    </br>'
        vResult += '    DirectX:<t><a href=\'http://htkb.dyndns.org/downloadsdirectx_Jun2010_redist.exe\'>Direct X Redistrutable</a></br>'
        vResult += '    DirectX \'Web\':<t><a href=\'http://htkb.dyndns.org/downloadsdxwebsetup.exe\'>Direct X Redistrutable</a></br>'
        vResult += '    </br>'
        vResult += '</p>'
    elif vKey == '3_2P':
        vResult = 'stub'
        vResult += 'stub'
        vResult += '<title>'
        vResult += '    Game Maker Downloads'
        vResult += '</title>'
        vResult += '<h2>'
        vResult += '    Game Maker Downloads'
        vResult += '</h2>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    Here are Game Maker Projects to play:</br>'
        vResult += '    </br>'
        vResult += '    \'Gamebox Client: v6.0\':<t><a href=\'http://htkb.dyndns.org/downloadsGameBox_Client_Installer_v6p0.exe\'>Play games from...well, anywhere.</a></br>'
        vResult += '    \'Gamebox Server: v6.0\':<t><a href=\'http://htkb.dyndns.org/downloadsGameBox_Server_Installer_v6p0.exe\'>Host GameBox.</a></br>'
        vResult += '    \'39dll.dll: v2.5:\'<t><a href=\'http://htkb.dyndns.org/downloads39dll.dll\'>You may need this in your \'useruser/AppData/Local/GameBox_Client\' folder.</a></br>'
        vResult += '    \'A Chess Client\':<t><a href=\'http://htkb.dyndns.org/downloadsChess_Client.exe\'>A game of Chess from anywhere.</a></br>'
        vResult += '    \'I Dunno\':<t><a href=\'http://htkb.dyndns.org/downloadsIdunno.exe\'>I dunno, it\'s a fun puzzle game though.</a></br>'
        vResult += '    \'Purification\':<t><a href=\'http://htkb.dyndns.org/downloadsZombies.exe\'>Kill zombies...lots of zombies.</a></br>'
        vResult += '    \'Trail of the Undead: The Way Home\':<t><a href=\'http://htkb.dyndns.org/downloadsTrailoftheUndead.exe\'>An adventure of zombie killing goodness.</a></br>'
        vResult += '    \'Discovery\' (buggy Alpha):<t><a href=\'http://htkb.dyndns.org/downloadsDiscovery.exe\'>Play a game of discovery and survival.</a></br>'
        vResult += '    \'Twisted Tactics: Version 0.1\' (buggy Alpha):<t><a href=\'http://htkb.dyndns.org/downloadsTactical.exe\'>Scrapped two player tactical system.</a></br>'
        vResult += '    \'Skitzo Burrito (Alpha): <t><a href=\'http://htkb.dyndns.org/downloadsEmotive-Default-1.0.0.3.exe\'>An emotional platform survival game.</a></br>'
        vResult += '</p>'
    elif vKey == '3_3P':
        vResult = '<title>'
        vResult += '    Java Downloads'
        vResult += '</title>'
        vResult += '<h2>'
        vResult += '    Java Downloads'
        vResult += '</h2>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    Here are Java Programs to download:</br>'
        vResult += '    </br>'
        vResult += '    \'Blood Bowl Manager\':<t><a href=\'http://htkb.dyndns.org/downloads/pichaku.zip\'>This is currently not available.</a></br>'
        vResult += '</p>'
    elif vKey == '3_4P':
        vResult = '<title>'
        vResult += '    C\# Downloads'
        vResult += '</title>'
        vResult += '<h2>'
        vResult += '    C\# Downloads'
        vResult += '</h2>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    Here are C\# Programs to download:</br>'
        vResult += '    </br>'
        vResult += '    \'Chess Program\':<t><a href=\'http://htkb.dyndns.org/downloads/pichaku.zip\'>This is currently not available.</a></br>'
        vResult += '</p>'
    elif vKey == '3_5P':
        vResult = '<title>'
        vResult += '    C++ Downloads'
        vResult += '</title>'
        vResult += '<h2>'
        vResult += '    C++ Downloads'
        vResult += '</h2>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += '    Here are C++ Programs to download:</br>'
        vResult += '    </br>'
        vResult += '    \'HTKB Bar Code System\':<t><a href=\'http://htkb.dyndns.org/downloads/pichaku.zip\'>This is currently not available.</a></br>'
        vResult += '</p>'
    else:
        vResult = '<title>HTKB Home Page</title>'
        vResult += '<h2>'
        vResult += 'Welcome to the House That Kamurai Built!'
        vResult += '</h2>'
        vResult += '<p id=\'idCenterContent\'>'
        vResult += 'The House That Kamurai Built is an '
        vResult += 'entertainment company with the primary '
        vResult += 'focus of increasing awesome by stimulating '
        vResult += 'intelligent conversation and entertainment '
        vResult += 'via discussion and game design. <br>'
        vResult += 'Increase the Awesome with us!<br>'
        vResult += '</p>'
    return vResult
