def getContent(vKey):
	if vKey == '0':
		vResult = '<title>HTKB Home Page</title>'
		vResult += '<h2>'
		vResult += '	Welcome to the House That Kamurai Built!'
		vResult += '</h2>'
		vResult += '<p id=\'idCenterContent\'>'
		vResult += '	The House That Kamurai Built is an '
		vResult += '	entertainment company with the primary '
		vResult += '	focus of increasing awesome by stimulating '
		vResult += '	intelligent conversation and entertainment '
		vResult += '	via discussion and game design. <br>'
		vResult += '	Increase the Awesome with us!<br>'
		vResult += '</p>'
	elif vKey == '0_1P':
		vResult = '<title>About Us</title>'
		vResult += '<h2>'
		vResult += '	About Us'
		vResult += '</h2>'
		vResult += '<p id=\'idCenterContent\'>'
		vResult += '	We are working to build this into a better place.</br>'
		vResult += '	If you found this, then you must be at least (Awesome/2).</br>'
		vResult += '	Stay tuned, right now it\'s all about laying foundation for the future.</br>'
		vResult += '</p>'
	elif vKey == '0_2P':
		vResult = '<title>Media</title>'
		vResult += '<h2>'
		vResult += '	Media'
		vResult += '</h2>'
		vResult += '<p id=\'idCenterContent\'>'
		vResult += '	You can find us at all these different places:</br>'
		vResult += '	<br/>'
		vResult += '	<br/>'
		vResult += '		#WeAreMovieClub:'
		vResult += '	<br/>'
		vResult += '	<br/>'
		vResult += '		<a href=\'http://www.youtube.com/WeAreMovieClub\'>Youtube.com/WeAreMovieClub:  A place for movie discussion.</a></br>'
		vResult += '		<a href=\'http://WeAreMovieClub.tumblr.com\'>WeAreMovieClub.tumblr.com: We have a tumblr!</a></br>'
		vResult += '		<a href=\'http://www.twitter.com/WeAreMovieClub\'>@WeAreMovieClub on Twitter: Let us know about your movie thoughts.</a></br>'
		vResult += '		<a href=\'http://www.facebook.com/WeAreMovieClub\'>facebook.com/WeAreMovieClub: Talk about movie with us.</a></br>'
		vResult += '	<br/>'
		vResult += '	<br/>'
		vResult += '		HTKB Productions'
		vResult += '	<br/>'
		vResult += '	<br/>'
		vResult += '		<a href=\'http://www.youtube.com/GamingDivision528\'>Gaming Division:  A Youtube Channel for game stuff.</a></br>'
		vResult += '		<a href=\'http://www.youtube.com/JamOnToast528\'>Jam On Toast:  A Youtube Channel for media stuff.</a></br>'
		vResult += '		<a href=\'http://www.ustream.tv/HTKB\'>UStream:  Streams show up here too.</a></br>'
		vResult += '		<a href=\'http://www.firetalk.com/HTKB\'>FireTalk:  Streams show up here too.</a></br>'
		vResult += '		<a href=\'http://www.younow.com/HTKB\'>YouNow:  Streams show up here too.</a></br>'
		vResult += '		<a href=\'http://www.soundcloud.com/HTKB\'>Sound Cloud:  Listen to our podcasts.</a></br>'
		vResult += '		<a href=\'http://HTKB.podbean.com/\'>Pod Bean:  Listen to our podcasts.</a></br>'
		vResult += '		<a href=\'http://www.youtube.com/HTKB\'>Youtube:  Thoughts and life discussions.</a></br>'
		vResult += '		<a href=\'http://www.patreon.com/HTKBProductions\'>Patreon:  You can help make our dreams reality.</a></br>'
		vResult += '		<a href=\'http://www.facebook.com/HouseThatKamuraiBuilt\'>Facebook: Talk about movie with us.</a></br>'
		vResult += '		<a href=\'http://HouseThatKamuraiBuilt.tumblr.com\'>HouseThatKamuraiBuilt.tumblr.com: We have a tumblr!</a></br>'
		vResult += '		<a href=\'http://myspace.com/HouseThatKamuraiBuilt\'>Myspace: Wow, there\'s even a MySpace!</a></br>'
		vResult += '	<br/>'
		vResult += '		Here are some of our member\'s pages:</br>'
		vResult += '	<br/>'
		vResult += '			Kamurai:'
		vResult += '	<br/>'
		vResult += '	<br/>'
		vResult += '		<a href=\'http://twitter.com/#!/Kamurai25\'>Kamurai\'s Twitter.</a></br>'
		vResult += '		<a href=\'http://Instagram.com/Kamurai25\'>Kamurai\'s Instagram.</a></br>'
		vResult += '		<a href=\'./.\'>Kamurai\'s Snapchat: Kamurai</a></br>'
		vResult += '		<a href=\'http://www.facebook.com/cris.kamurai\'>Kamurai\'s Facebook.</a></br>'
		vResult += '		<a href=\'https://www.gplus.com/Members/Cris-Kamurai\'>Kamurai\'s Google Plus.</a></br>'
		vResult += '		<a href=\'http://www.yoyogames.com/users/Kamurai\'>Kamurai\'s YoYo Games page:  See some of the games he\'s posted.</a></br>'
		vResult += '</p>'
	elif vKey == '0_3P':
		vResult = '<title>Minecraft!</title>'
		vResult += '<h2>'
		vResult += '	Minecraft!'
		vResult += '</h2>'
		vResult += '	<p id=\'idCenterContent\'>'
		vResult += '		If you would like to play Minecraft with us, we have several different servers:</br>'
		vResult += '		Mo Creatures Server: (1.7.10) htkb.dyndns.org:25565</br>'
		vResult += '		Creative Server:     (1.7.10) htkb.dyndns.org:25567</br>'
		vResult += '			This is a list of mods that we are using on the server, compatible with 1.7.10.</br>'
		vResult += '			<a href=\'./Downloads/Minecraft/forge-1.7.10-10.13.3.1401-1710ls-installer.jar\'>Forge 1.7.10</a></br>'
		vResult += '			<a href=\'./Downloads/Minecraft/DrZharks MoCreatures Mod v6.3.1.zip\'>Dr Zhark\'s Mo Creatures</a></br>'
		vResult += '			<a href=\'./Downloads/Minecraft/CustomMobSpawner 3.3.0.zip\'>Custom Mob Spawner</a></br>'
		vResult += '			<a href=\'./Downloads/Minecraft/[1.7.10]Gender-1.0.2.jar\'>iPixeli\'s Gender Mod</a></br>'
		vResult += '			<a href=\'./Downloads/Minecraft/BspkrsCore-1.7.10.jar\'>Bspkrs Core</a></br>'
		vResult += '			<a href=\'./Downloads/Minecraft/[1.7.10]Treecapitator-universal-2.0.4.jar\'>Tree Capitator</a></br>'
		vResult += '			<a href=\'./Downloads/Minecraft/MoarFood-5.8.0.jar\'>Moar Food</a></br>'
		vResult += '			<a href=\'./Downloads/Minecraft/MoarOres-2.4.5.jar\'>Moar Ores</a></br>'
		vResult += '			<a href=\'./Downloads/Minecraft/BiblioCraft[v1.10.4][MC1.7.10].jar\'>Biblio Craft</a></br>'
		vResult += '			<a href=\'./Downloads/Minecraft/Fossils_Archeology_Revival-1.7.10_Build-6.4b.jar\'>Fossils and Archaeology</a></br>'
		vResult += '			<a href=\'./Downloads/Minecraft/Reis-Minimap-Mod-1.7.10.jar\'>Rei\'s Minimap</a></br>'
		vResult += '			<a href=\'./Downloads/Minecraft/Xaeros_Minimap_1.10.8_Forge_1.7.10.jar\'>Xaero\'s Minimap</a></br>'
		vResult += '		Vanilla Server:      htkb.dyndns.org:25566</br>'
		vResult += '		Here is a skin template to make custom skins:</br>'
		vResult += '		<a href=\'./Downloads/Minecraft/skin_template.png\'>Steve skin template</a></br>'
		vResult += '		<br/>'
		vResult += '		<br/>'
		vResult += '		For first time setups, please follow these steps to make your client compatible with the server:</br>'
		vResult += '			 0) If you don\'t have Minecraft, go to Minecraft.net and download the latest version of the launcher.</br>'
		vResult += '			 1) From the launcher create a new profile and change its version to the relevant version (e.g. 1.7.10).</br>'
		vResult += '			 2) Save the Profile, select the new profile and click play.</br>'
		vResult += '			 3) Exit the program.</br>'
		vResult += '			 4) Install Forge.  If it is not automatically selected, then browse to your .minecraft folder.</br>'
		vResult += '				Windows: It is in a hidden folder: c:\Users\*Username*\Appdata\Roaming\.minecraft</br>'
		vResult += '				Mac: \'Go to\' ~/Library/Application Support/minecraft</br>'
		vResult += '			 5) If you are managing multiple non-compatible mods, then you man have to make folders like:</br>'
		vResult += '				\'..\Roaming\MoCreatures\'</br>'
		vResult += '			 6) If your folder doesn\'t have a /Mods folder, create one. Place the files from the mod list into the /mods folder.</br>'
		vResult += '				Even if it works, don\'t put two minimap mods in the same folder.</br>'
		vResult += '			 7) Open the Minecraft Launcher, edit your version (e.g. 1.7.10) profile to use the forge version of the same.</br>'
		vResult += '			 8) If you are using a different folder, then remember to change the Game Directory in the profile.</br>'
		vResult += '			 9) Save the Profile, select the new profile and click play.</br>'
		vResult += '			10) You should see the mods listed on the side of the Minecraft window.</br>'
		vResult += '			11) Go to multiplayer and click add server.</br>'
		vResult += '			12) Name the server something distinct and put \'htkb.dyndns.org:2556x\' in the address bar where \'x\' is the relevant port.</br>'
		vResult += '			13) Save the server entry.  You should see a connection to the server.  Double click to join.</br>'
		vResult += '	</p>'
	elif vKey == '1':
		vResult = 'stub'
		vResult += 'stub'
	elif vKey == '1_2':
		vResult = 'stub'
		vResult += 'stub'
	elif vKey == '1_4':
		vResult = 'stub'
		vResult += 'stub'
	elif vKey == '1_5':
		vResult = 'stub'
		vResult += 'stub'
	elif vKey == '1_6':
		vResult = 'stub'
		vResult += 'stub'
	elif vKey == '2':
		vResult = 'stub'
		vResult += 'stub'
	elif vKey == '2_1':
		vResult = 'stub'
		vResult += 'stub'
	elif vKey == '2_4':
		vResult = 'stub'
		vResult += 'stub'
	elif vKey == '2_5':
		vResult = 'stub'
		vResult += 'stub'
	elif vKey == '2_5_1':
		vResult = 'stub'
		vResult += 'stub'
	elif vKey == '2_5_2':
		vResult = 'stub'
		vResult += 'stub'
	elif vKey == '2_5_3':
		vResult = 'stub'
		vResult += 'stub'
	elif vKey == '2_5_4':
		vResult = 'stub'
		vResult += 'stub'
	elif vKey == '2_6':
		vResult = 'stub'
		vResult += 'stub'
	elif vKey == '2_6_2':
		vResult = 'stub'
		vResult += 'stub'
	elif vKey == '2_6_2_2':
		vResult = 'stub'
		vResult += 'stub'
	elif vKey == '3':
		vResult = 'stub'
		vResult += 'stub'
		vResult += '<title>'
		vResult += '	Downloadable Projects'
		vResult += '</title>'
		vResult += '<h1>'
		vResult += '	Downloadable Projects'
		vResult += '</h1>'
		vResult += '<p  id=\"idCenterContent\">'
		vResult += '	This section is dedicated to downloadable projects.'
		vResult += '</p>'
	elif vKey == '3_1P':
		vResult = '<title>'
		vResult += '	Online Experience Downloads'
		vResult += '</title>'
		vResult += '<h2>'
		vResult += '	Online Experience Downloads'
		vResult += '</h2>'
		vResult += '<p id=\"idCenterContent\">'
		vResult += '	Here are downloads to play Cube World with us:</br>'
		vResult += '	</br>'
		vResult += '	Cube World:<t><a href=\"http://htkb.dyndns.org/downloadsCubeSetup3.exe\">Come play Cube World!</a></br>'
		vResult += '	</br>'
		vResult += '	DirectX:<t><a href=\"http://htkb.dyndns.org/downloadsdirectx_Jun2010_redist.exe\">Direct X Redistrutable</a></br>'
		vResult += '	DirectX "Web":<t><a href=\"http://htkb.dyndns.org/downloadsdxwebsetup.exe\">Direct X Redistrutable</a></br>'
		vResult += '	</br>'
		vResult += '</p>'
	elif vKey == '3_2P':
		vResult = 'stub'
		vResult += 'stub'
		vResult += '<title>'
		vResult += '	Game Maker Downloads'
		vResult += '</title>'
		vResult += '<h2>'
		vResult += '	Game Maker Downloads'
		vResult += '</h2>'
		vResult += '<p id=\"idCenterContent\">'
		vResult += '	Here are Game Maker Projects to play:</br>'
		vResult += '	</br>'
		vResult += '	\"Gamebox Client: v6.0\":<t><a href=\"http://htkb.dyndns.org/downloadsGameBox_Client_Installer_v6p0.exe\">Play games from...well, anywhere.</a></br>'
		vResult += '	\"Gamebox Server: v6.0\":<t><a href=\"http://htkb.dyndns.org/downloadsGameBox_Server_Installer_v6p0.exe\">Host GameBox.</a></br>'
		vResult += '	\"39dll.dll: v2.5:\"<t><a href=\"http://htkb.dyndns.org/downloads39dll.dll\">You may need this in your \"useruser/AppData/Local/GameBox_Client\" folder.</a></br>'
		vResult += '	\"A Chess Client\":<t><a href=\"http://htkb.dyndns.org/downloadsChess_Client.exe\">A game of Chess from anywhere.</a></br>'
		vResult += '	\"I Dunno\":<t><a href=\"http://htkb.dyndns.org/downloadsIdunno.exe\">I dunno, it\'s a fun puzzle game though.</a></br>'
		vResult += '	\"Purification\":<t><a href=\"http://htkb.dyndns.org/downloadsZombies.exe\">Kill zombies...lots of zombies.</a></br>'
		vResult += '	\"Trail of the Undead: The Way Home\":<t><a href=\"http://htkb.dyndns.org/downloadsTrailoftheUndead.exe\">An adventure of zombie killing goodness.</a></br>'
		vResult += '	\"Discovery\" (buggy Alpha):<t><a href=\"http://htkb.dyndns.org/downloadsDiscovery.exe\">Play a game of discovery and survival.</a></br>'
		vResult += '	\"Twisted Tactics: Version 0.1\" (buggy Alpha):<t><a href=\"http://htkb.dyndns.org/downloadsTactical.exe\">Scrapped two player tactical system.</a></br>'
		vResult += '	\"Skitzo Burrito (Alpha): <t><a href=\"http://htkb.dyndns.org/downloadsEmotive-Default-1.0.0.3.exe\">An emotional platform survival game.</a></br>'
		vResult += '</p>'
	elif vKey == '3_3P':
		vResult = '<title>'
			vResult += 'Java Downloads'
		vResult += '</title>'
		vResult += '<h2>'
			vResult += 'Java Downloads'
		vResult += '</h2>'
		vResult += '<p id=\"idCenterContent\">'
			vResult += 'Here are Java Programs to download:</br>'
			vResult += '</br>'
			vResult += '\"Blood Bowl Manager\":<t><a href=\"http://htkb.dyndns.org/downloads/pichaku.zip\">This is currently not available.</a></br>'
		vResult += '</p>'
	elif vKey == '3_4P':
		vResult = '<title>'
		vResult += '	C\# Downloads'
		vResult += '</title>'
		vResult += '<h2>'
		vResult += '	C\# Downloads'
		vResult += '</h2>'
		vResult += '<p id=\"idCenterContent\">'
		vResult += '	Here are C\# Programs to download:</br>'
		vResult += '	</br>'
		vResult += '	"Chess Program":<t><a href=\"http://htkb.dyndns.org/downloads/pichaku.zip\">This is currently not available.</a></br>'
		vResult += '</p>'
	elif vKey == '3_5P':
		vResult = '<title>'
		vResult += '	C++ Downloads'
		vResult += '</title>'
		vResult += '<h2>'
		vResult += '	C++ Downloads'
		vResult += '</h2>'
		vResult += '<p id="idCenterContent">'
		vResult += '	Here are C++ Programs to download:</br>'
		vResult += '	</br>'
		vResult += '	\"HTKB Bar Code System\":<t><a href=\"http://htkb.dyndns.org/downloads/pichaku.zip\">This is currently not available.</a></br>'
		vResult += '</p>'
	else:
		vResult = '<title>HTKB Home Page</title>'
		vResult += '<h2>'
		vResult += 'Welcome to the House That Kamurai Built!'
		vResult += '</h2>'
		vResult += '<p id=\'idCenterContent\'>'
		vResult += 'The House That Kamurai Built is an '
		vResult += 'entertainment company with the primary '
		vResult += 'focus of increasing awesome by stimulating '
		vResult += 'intelligent conversation and entertainment '
		vResult += 'via discussion and game design. <br>'
		vResult += 'Increase the Awesome with us!<br>'
		vResult += '</p>'
	return vResult

