def getNavigation(vLevel):
	if vLevel == '0':
		vResult = '<a class=\'navlinkA\' href=\'/AboutUs\'>About Us</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Media\'>Media</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Minecraft\'>Minecraft!</a></br></br>'
	elif vLevel == '1':
		vResult = '<a class=\'navlinkA\' href=\'http://htkb.dyndns.org/Section1/index.html\'>Basic HTML</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'http://htkb.dyndns.org/Section1/Project1.php\'>PHP</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section1/Section2/index\'>Java Script</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'http://htkb.dyndns.org/Section1/Project3.shtml\'>Perl</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section1/Section4/index\'>Java</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section1/Section5/index\'>ASP.Net</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section1/Section6/index\'>Databases</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'http://htkb.dyndns.org/SSI/Section1/index.html\'>Apache SSI</a></br></br>'
	elif vLevel == '1_2':
		vResult = '<a class=\'navlinkA\' href=\'http://htkb.dyndns.org/Section1/index.html\'>Basic HTML</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'http://htkb.dyndns.org/Section1/Project1.php\'>PHP</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section1/Section2/index\'>Java Script</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'../../Javascript/Section1/Section2/Project1.html\'>HTML Javascript</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'http://htkb.dyndns.org:81/ASP/Section1/Section2/Project2.asp\'>ASP Javascript</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'http://htkb.dyndns.org:81/ASPNET/Section1/Section2/Project3.aspx\'>ASP.NET Javascript</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'http://htkb.dyndns.org/Section1/Project3.shtml\'>Perl</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'Section1/Section4/index\'>Java</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'Section1/Section5/index\'>ASP.Net</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'Section1/Section6/index\'>Databases</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'http://htkb.dyndns.org/SSI/Section1/index.html\'>Apache SSI</a></br></br>'
	elif vLevel == '1_4':
		vResult = '<a class=\'navlinkA\' href=\'http://htkb.dyndns.org/Section1/index.html\'>Basic HTML</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'http://htkb.dyndns.org/Section1/Project1.php\'>PHP</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section1/Section2/index\'>Java Script</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'http://htkb.dyndns.org/Section1/Project3.shtml\'>Perl</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'Section1/Section4/index\'>Java</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'http://htkb.dyndns.org:8080/JSPApplication/Section1/Section4/Project1.jsp\'>JSP Programming</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'http://htkb.dyndns.org:8080/JSFApplication/Section1/Section4/Project2.xhtml\'>JSF Programming</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'Section1/Section5/index\'>ASP.Net</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'Section1/Section6/index\'>Databases</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'http://htkb.dyndns.org/SSI/Section1/index.html\'>Apache SSI</a></br></br>'
	elif vLevel == '1_5':
		vResult = '<a class=\'navlinkA\' href=\'http://htkb.dyndns.org/Section1/index.html\'>Basic HTML</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'http://htkb.dyndns.org/Section1/Project1.php\'>PHP</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section1/Section2/index\'>Java Script</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'http://htkb.dyndns.org/Section1/Project3.shtml\'>Perl</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'Section1/Section4/index\'>Java</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'Section1/Section5/index\'>ASP.Net</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'http://htkb.dyndns.org:81/WebApplication/Section1/Section5/Project1.cshtml\'>Webpage Application</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'http://htkb.dyndns.org:81/WebForm/Section1/Section5/Project2.aspx\'>Webform Application</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'http://htkb.dyndns.org:81/MVC/Section1_5/Project3\'>MVC Application</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'Section1/Section6/index\'>Databases</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'http://htkb.dyndns.org/SSI/Section1/index.html\'>Apache SSI</a></br></br>'
	elif vLevel == '1_6':
		vResult = '<a class=\'navlinkA\' href=\'http://htkb.dyndns.org/Section1/index.html\'>Basic HTML</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'http://htkb.dyndns.org/Section1/Project1.php\'>PHP</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section1/Section2/index\'>Java Script</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'http://htkb.dyndns.org/Section1/Project3.shtml\'>Perl</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'Section1/Section4/index\'>Java</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'Section1/Section5/index\'>ASP.Net</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'Section1/Section6/index\'>Databases</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'Section1/Section6/Project1.html\'>Oracle</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'Section1/Section6/Project2.html\'>Derby</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'Section1/Section6/Project3.html\'>MySQL</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'Section1/Section6/Project4.html\'>Postgres</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'http://htkb.dyndns.org/SSI/Section1/index.html\'>Apache SSI</a></br></br>'
	elif vLevel == '2':
		vResult = '<a class=\'navlinkA\' href=\'/Section2/Section1/index.html\'>Gynowars</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project2.html\'>Assault</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project3.html\'>Mars</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Section4/index.html\'>Renley</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Section5/index.html\'>Antarrea</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Section6/index.html\'>Editations</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project7.html\'>Truth</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project8.html\'>Kingdoms</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project9.html\'>Terminal World</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project10.html\'>Monster Office Workplace</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project11.html\'>Battle Princesses</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project12.html\'>Sacred Offerings</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project13.html\'>The Way</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project14.html\'>Conspiratorium</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project15.html\'>Conversion</a></br></br>'
	elif vLevel == '2_1':
		vResult = '<a class=\'navlinkA\' href=\'/Section2/Section1/index.html\'>Gynowars</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section1/Project1.html\'>Gynowars RPG</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section1/Project2.html\'>Gynowars: Battle Arena CCG</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section1/Project3.html\'>Gynowars: Crash Ball</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project2.html\'>Assault</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project3.html\'>Mars</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Section4/index.html\'>Renley</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Section5/index.html\'>Antarrea</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Section6/index.html\'>Editations</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project7.html\'>Truth</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project8.html\'>Kingdoms</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project9.html\'>Terminal World</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project10.html\'>Monster Office Workplace</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project11.html\'>Battle Princesses</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project12.html\'>Sacred Offerings</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project13.html\'>The Way</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project14.html\'>Conspiratorium</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project15.html\'>Conversion</a></br></br>'
	elif vLevel == '2_4':
		vResult = '<a class=\'navlinkA\' href=\'/Section2/Section1/index.html\'>Gynowars</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project2.html\'>Assault</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project3.html\'>Mars</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Section4/index.html\'>Renley</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section4/Project1.html\'>Warring Nations</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section4/Project2.html\'>Psychodom: The One Empire</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Section5/index.html\'>Antarrea</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Section6/index.html\'>Editations</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project7.html\'>Truth</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project8.html\'>Kingdoms</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project9.html\'>Terminal World</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project10.html\'>Monster Office Workplace</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project11.html\'>Battle Princesses</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project12.html\'>Sacred Offerings</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project13.html\'>The Way</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project14.html\'>Conspiratorium</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project15.html\'>Conversion</a></br></br>'
	elif vLevel == '2_5':
		vResult = '<a class=\'navlinkA\' href=\'/Section2/Section1/index.html\'>Gynowars</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project2.html\'>Assault</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project3.html\'>Mars</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Section4/index.html\'>Renley</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Section5/index.html\'>Antarrea</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section5/Section1/index.html\'>Global</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section5/Section2/index.html\'>Grendol</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section5/Section3/index.html\'>Utopia</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section5/Section4/index.html\'>Elvia</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Section6/index.html\'>Editations</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project7.html\'>Truth</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project8.html\'>Kingdoms</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project9.html\'>Terminal World</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project10.html\'>Monster Office Workplace</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project11.html\'>Battle Princesses</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project12.html\'>Sacred Offerings</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project13.html\'>The Way</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project14.html\'>Conspiratorium</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project15.html\'>Conversion</a></br></br>'
	elif vLevel == '2_5_1':
		vResult = '<a class=\'navlinkA\' href=\'/Section2/Section1/index.html\'>Gynowars</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project2.html\'>Assault</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project3.html\'>Mars</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Section4/index.html\'>Renley</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Section5/index.html\'>Antarrea</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section5/Section1/index.html\'>Global</a></br></br>'
		vResult += '		<a class=\'navlinkC\' href=\'/Section2/Section5/Section1/Project1.html\'>Team Tactial: Crash Ball</a></br></br>'
		vResult += '		<a class=\'navlinkC\' href=\'/Section2/Section5/Section1/Project2.html\'>Wars of Antarrea</a></br></br>'
		vResult += '		<a class=\'navlinkC\' href=\'/Section2/Section5/Section1/Project3.html\'>Revolutions: Invading Nations:</a></br></br>'
		vResult += '		<a class=\'navlinkC\' href=\'/Section2/Section5/Section1/Project4.html\'>Revolutions: Rebellion Against the Fist</a></br></br>'
		vResult += '		<a class=\'navlinkC\' href=\'/Section2/Section5/Section1/Project5.html\'>Revolutions: Return to Arms</a></br></br>'
		vResult += '		<a class=\'navlinkC\' href=\'/Section2/Section5/Section1/Project6.html\'>Revolutions: Post Wars</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section5/Section2/index.html\'>Grendol</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section5/Section3/index.html\'>Utopia</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section5/Section4/index.html\'>Elvia</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Section6/index.html\'>Editations</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project7.html\'>Truth</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project8.html\'>Kingdoms</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project9.html\'>Terminal World</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project10.html\'>Monster Office Workplace</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project11.html\'>Battle Princesses</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project12.html\'>Sacred Offerings</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project13.html\'>The Way</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project14.html\'>Conspiratorium</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project15.html\'>Conversion</a></br></br>'
	elif vLevel == '2_5_2':
		vResult = '<a class=\'navlinkA\' href=\'/Section2/Section1/index.html\'>Gynowars</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project2.html\'>Assault</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project3.html\'>Mars</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Section4/index.html\'>Renley</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Section5/index.html\'>Antarrea</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section5/Section1/index.html\'>Global</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section5/Section2/index.html\'>Grendol</a></br></br>'
		vResult += '		<a class=\'navlinkC\' href=\'/Section2/Section5/Section2/Project1.html\'>Land of the Orcish Empire: Age of Magic</a></br></br>'
		vResult += '		<a class=\'navlinkC\' href=\'/Section2/Section5/Section2/Project2.html\'>Coliseum: Arena</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section5/Section3/index.html\'>Utopia</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section5/Section4/index.html\'>Elvia</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Section6/index.html\'>Editations</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project7.html\'>Truth</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project8.html\'>Kingdoms</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project9.html\'>Terminal World</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project10.html\'>Monster Office Workplace</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project11.html\'>Battle Princesses</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project12.html\'>Sacred Offerings</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project13.html\'>The Way</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project14.html\'>Conspiratorium</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project15.html\'>Conversion</a></br></br>'
	elif vLevel == '2_5_3':
		vResult = '<a class=\'navlinkA\' href=\'/Section2/Section1/index.html\'>Gynowars</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project2.html\'>Assault</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project3.html\'>Mars</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Section4/index.html\'>Renley</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Section5/index.html\'>Antarrea</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section5/Section1/index.html\'>Global</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section5/Section2/index.html\'>Grendol</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section5/Section3/index.html\'>Utopia</a></br></br>'
		vResult += '		<a class=\'navlinkC\' href=\'/Section2/Section5/Section3/Project1.html\'>Avia:Elemental Angels</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section5/Section4/index.html\'>Elvia</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Section6/index.html\'>Editations</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project7.html\'>Truth</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project8.html\'>Kingdoms</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project9.html\'>Terminal World</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project10.html\'>Monster Office Workplace</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project11.html\'>Battle Princesses</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project12.html\'>Sacred Offerings</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project13.html\'>The Way</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project14.html\'>Conspiratorium</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project15.html\'>Conversion</a></br></br>'
	elif vLevel == '2_5_4':
		vResult = '<a class=\'navlinkA\' href=\'/Section2/Section1/index.html\'>Gynowars</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project2.html\'>Assault</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project3.html\'>Mars</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Section4/index.html\'>Renley</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Section5/index.html\'>Antarrea</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section5/Section1/index.html\'>Global</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section5/Section2/index.html\'>Grendol</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section5/Section3/index.html\'>Utopia</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section5/Section4/index.html\'>Elvia</a></br></br>'
		vResult += '		<a class=\'navlinkC\' href=\'/Section2/Section5/Section4/Project1.html\'>Nine Card</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Section6/index.html\'>Editations</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project7.html\'>Truth</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project8.html\'>Kingdoms</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project9.html\'>Terminal World</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project10.html\'>Monster Office Workplace</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project11.html\'>Battle Princesses</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project12.html\'>Sacred Offerings</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project13.html\'>The Way</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project14.html\'>Conspiratorium</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project15.html\'>Conversion</a></br></br>'
	elif vLevel == '2_6':
		vResult = '<a class=\'navlinkA\' href=\'/Section2/Section1/index.html\'>Gynowars</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project2.html\'>Assault</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project3.html\'>Mars</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Section4/index.html\'>Renley</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Section5/index.html\'>Antarrea</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Section6/index.html\'>Editations</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section6/Project1.html\'>Magic: The Tactical</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section6/Section2/index.html\'>Warhammer 40K</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project7.html\'>Truth</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project8.html\'>Kingdoms</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project9.html\'>Terminal World</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project10.html\'>Monster Office Workplace</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project11.html\'>Battle Princesses</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project12.html\'>Sacred Offerings</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project13.html\'>The Way</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project14.html\'>Conspiratorium</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project15.html\'>Conversion</a></br></br>'
	elif vLevel == '2_6_2':
		vResult = '<a class=\'navlinkA\' href=\'/Section2/Section1/index.html\'>Gynowars</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project2.html\'>Assault</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project3.html\'>Mars</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Section4/index.html\'>Renley</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Section5/index.html\'>Antarrea</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Section6/index.html\'>Editations</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section6/Project1.html\'>Magic: The Tactical</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section6/Section2/index.html\'>Warhammer 40K</a></br></br>'
		vResult += '		<a class=\'navlinkC\' href=\'/Section2/Section6/Section2/Project1.html\'>Mission!</a></br></br>'
		vResult += '		<a class=\'navlinkC\' href=\'/Section2/Section6/Section2/Section2/index.html\'>HTKB Armies</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project7.html\'>Truth</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project8.html\'>Kingdoms</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project9.html\'>Terminal World</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project10.html\'>Monster Office Workplace</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project11.html\'>Battle Princesses</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project12.html\'>Sacred Offerings</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project13.html\'>The Way</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project14.html\'>Conspiratorium</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project15.html\'>Conversion</a></br></br>'
	elif vLevel == '2_6_2_2':
		vResult = '<a class=\'navlinkA\' href=\'/Section2/Section1/index.html\'>Gynowars</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project2.html\'>Assault</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project3.html\'>Mars</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Section4/index.html\'>Renley</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Section5/index.html\'>Antarrea</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Section6/index.html\'>Editations</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section6/Project1.html\'>Magic: The Tactical</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section6/Section2/index.html\'>Warhammer 40K</a></br></br>'
		vResult += '		<a class=\'navlinkC\' href=\'/Section2/Section6/Section2/Project1.html\'>Mission!</a></br></br>'
		vResult += '		<a class=\'navlinkC\' href=\'/Section2/Section6/Section2/Section2/index.html\'>HTKB Armies</a></br></br>'
		vResult += '			<a class=\'navlinkD\' href=\'/Section2/Section6/Section2/Section2/Project1.html\'>Ad Infinitum</a></br></br>'
		vResult += '			<a class=\'navlinkD\' href=\'/Section2/Section6/Section2/Section2/Project2.html\'>Avia</a></br></br>'
		vResult += '			<a class=\'navlinkD\' href=\'/Section2/Section6/Section2/Section2/Project3.html\'>De Luna</a></br></br>'
		vResult += '			<a class=\'navlinkD\' href=\'/Section2/Section6/Section2/Section2/Project4.html\'>Eve</a></br></br>'
		vResult += '			<a class=\'navlinkD\' href=\'/Section2/Section6/Section2/Section2/Project5.html\'>Geo Marines</a></br></br>'
		vResult += '			<a class=\'navlinkD\' href=\'/Section2/Section6/Section2/Section2/Project6.html\'>Twin Fists</a></br></br>'
		vResult += '			<a class=\'navlinkD\' href=\'/Section2/Section6/Section2/Section2/Project7.html\'>Voboulids</a></br></br>'
		vResult += '			<a class=\'navlinkD\' href=\'/Section2/Section6/Section2/Section2/Project8.html\'>Fungi</a></br></br>'
		vResult += '			<a class=\'navlinkD\' href=\'/Section2/Section6/Section2/Section2/Project9.html\'>Synergy</a></br></br>'
		vResult += '			<a class=\'navlinkD\' href=\'/Section2/Section6/Section2/Section2/Project10.html\'>The Dark</a></br></br>'
		vResult += '			<a class=\'navlinkD\' href=\'/Section2/Section6/Section2/Section2/Project11.html\'>Vivus Mortem</a></br></br>'
		#/indent
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project7.html\'>Truth</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project8.html\'>Kingdoms</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project9.html\'>Terminal World</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project10.html\'>Monster Office Workplace</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project11.html\'>Battle Princesses</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project12.html\'>Sacred Offerings</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project13.html\'>The Way</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project14.html\'>Conspiratorium</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project15.html\'>Conversion</a></br></br>'
	elif vLevel == '3':
		vResult = '<a class=\'navlinkA\' href=\'/Section3/Project1\'>Online Experience Downloads</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section3/Project2\'>Game Maker Downloads</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section3/Project3\'>Java Downloads</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section3/Project4\'>C# Downloads</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section3/Project5\'>C++ Downloads</a></br></br>'
	else:
		vResult = '<a class=\'navlinkA\' href=\'/AboutUs\'>About Us</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Media\'>Media</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Minecraft\'>Minecraft!</a></br></br>'
	return vResult

