def getNavigation(vKey):
	if vKey == '0':
		vResult = '<a class=\'navlinkA\' href=\'/AboutUs\'>About Us</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Media\'>Media</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Minecraft\'>Minecraft!</a></br></br>'
	elif vKey == '1':
		vResult = '<a class=\'navlinkA\' href=\'http://htkb.dyndns.org/Section1/Index.html\'>Basic HTML</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'http://htkb.dyndns.org/Section1/Index.php\'>PHP</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'http://htkb.dyndns.org/Javascript/Section1/Section2/Index\'>Java Script</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'http://htkb.dyndns.org/Section1/Index.shtml\'>Perl</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section1/Section4/Index\'>Java</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section1/Section5/Index\'>ASP.Net</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section1/Section6/Index\'>Databases</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'http://htkb.dyndns.org/SSI/Section1/Index.html\'>Apache SSI</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'http://htkb.dyndns.org:83/Section1/Index\'>Ruby on Rails</a></br></br>'
	elif vKey == '1_2':
		vResult = '<a class=\'navlinkA\' href=\'http://htkb.dyndns.org/Section1/Index.html\'>Basic HTML</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'http://htkb.dyndns.org/Section1/Index.php\'>PHP</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section1/Section2/Index\'>Java Script</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'http://htkb.dyndns.org/Javascript/Section1/Section2/Index.html\'>HTML Javascript</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'http://htkb.dyndns.org/JQuery/Section1/Section2/Index.html\'>JQuery</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'http://htkb.dyndns.org:81/ASP/Section1/Section2/Index.asp\'>ASP Javascript</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'http://htkb.dyndns.org:81/ASPNET/Section1/Section2/Index.aspx\'>ASP.NET Javascript</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'http://htkb.dyndns.org:84/Section1/Section2/Index\'>Node JS</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'http://htkb.dyndns.org/Section1/Index.shtml\'>Perl</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section1/Section4/Index\'>Java</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section1/Section5/Index\'>ASP.Net</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section1/Section6/Index\'>Databases</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'http://htkb.dyndns.org/SSI/Section1/Index.html\'>Apache SSI</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'http://htkb.dyndns.org:83/Section1/Index\'>Ruby on Rails</a></br></br>'
	elif vKey == '1_4':
		vResult = '<a class=\'navlinkA\' href=\'http://htkb.dyndns.org/Section1/Index.html\'>Basic HTML</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'http://htkb.dyndns.org/Section1/Index.php\'>PHP</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section1/Section2/Index\'>Java Script</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'http://htkb.dyndns.org/Section1/Index.shtml\'>Perl</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section1/Section4/Index\'>Java</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'http://htkb.dyndns.org:8080/JSPApplication/Section1/Section4/Index.jsp\'>JSP Programming</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'http://htkb.dyndns.org:8080/JSFApplication/Section1/Section4/Index.xhtml\'>JSF Programming</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section1/Section5/Index\'>ASP.Net</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section1/Section6/Index\'>Databases</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'http://htkb.dyndns.org/SSI/Section1/Index.html\'>Apache SSI</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'http://htkb.dyndns.org:83/Section1/Index\'>Ruby on Rails</a></br></br>'
	elif vKey == '1_5':
		vResult = '<a class=\'navlinkA\' href=\'http://htkb.dyndns.org/Section1/Index.html\'>Basic HTML</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'http://htkb.dyndns.org/Section1/Index.php\'>PHP</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section1/Section2/Index\'>Java Script</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'http://htkb.dyndns.org/Section1/Index.shtml\'>Perl</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section1/Section4/Index\'>Java</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section1/Section5/Index\'>ASP.Net</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'http://htkb.dyndns.org:81/WebApplication/Section1/Section5/Index.cshtml\'>Webpage Application</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'http://htkb.dyndns.org:81/WebForm/Section1/Section5/Index.aspx\'>Webform Application</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'http://htkb.dyndns.org:81/MVC/Section1_5/Index\'>MVC Application</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section1/Section6/Index\'>Databases</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'http://htkb.dyndns.org/SSI/Section1/Index.html\'>Apache SSI</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'http://htkb.dyndns.org:83/Section1/Index\'>Ruby on Rails</a></br></br>'
	elif vKey == '1_6':
		vResult = '<a class=\'navlinkA\' href=\'http://htkb.dyndns.org/Section1/Index.html\'>Basic HTML</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'http://htkb.dyndns.org/Section1/Index.php\'>PHP</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section1/Section2/Index\'>Java Script</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'http://htkb.dyndns.org/Section1/Index.shtml\'>Perl</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section1/Section4/Index\'>Java</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section1/Section5/Index\'>ASP.Net</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section1/Section6/Index\'>Databases</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section1/Section6/Project1\'>Oracle</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section1/Section6/Project2\'>Derby</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section1/Section6/Project3\'>MySQL</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section1/Section6/Project4\'>SQL Server</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section1/Section6/Project5\'>Postgres</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'http://htkb.dyndns.org/SSI/Section1/Index.html\'>Apache SSI</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'http://htkb.dyndns.org:83/Section1/Index\'>Ruby on Rails</a></br></br>'
	elif vKey == '2':
		vResult = '<a class=\'navlinkA\' href=\'/Section2/Section1/Index\'>Gynowars</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project2\'>Assault</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project3\'>Mars</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Section4/Index\'>Renley</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Section5/Index\'>Antarrea</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project6\'>Truth</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project7\'>Kingdoms</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project8\'>Terminal World</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project9\'>Monster Office Workplace</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project10\'>Battle Princesses</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project11\'>Sacred Offerings</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project12\'>The Way</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project13\'>Conspiratorium</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project14\'>Conversion</a></br></br>'
	elif vKey == '2_1':
		vResult = '<a class=\'navlinkA\' href=\'/Section2/Section1/Index\'>Gynowars</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section1/Project1\'>Gynowars RPG</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section1/Project2\'>Gynowars: Battle Arena CCG</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section1/Project3\'>Gynowars: Crash Ball</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project2\'>Assault</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project3\'>Mars</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Section4/Index\'>Renley</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Section5/Index\'>Antarrea</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project6\'>Truth</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project7\'>Kingdoms</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project8\'>Terminal World</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project9\'>Monster Office Workplace</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project10\'>Battle Princesses</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project11\'>Sacred Offerings</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project12\'>The Way</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project13\'>Conspiratorium</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project14\'>Conversion</a></br></br>'
	elif vKey == '2_4':
		vResult = '<a class=\'navlinkA\' href=\'/Section2/Section1/Index\'>Gynowars</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project2\'>Assault</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project3\'>Mars</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Section4/Index\'>Renley</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section4/Project1\'>Warring Nations</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section4/Project2\'>Psychodom: The One Empire</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Section5/Index\'>Antarrea</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project6\'>Truth</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project7\'>Kingdoms</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project8\'>Terminal World</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project9\'>Monster Office Workplace</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project10\'>Battle Princesses</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project11\'>Sacred Offerings</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project12\'>The Way</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project13\'>Conspiratorium</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project14\'>Conversion</a></br></br>'
	elif vKey == '2_5':
		vResult = '<a class=\'navlinkA\' href=\'/Section2/Section1/Index\'>Gynowars</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project2\'>Assault</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project3\'>Mars</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Section4/Index\'>Renley</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Section5/Index\'>Antarrea</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section5/Section1/Index\'>Global</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section5/Section2/Index\'>Grendol</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section5/Section3/Index\'>Utopia</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section5/Section4/Index\'>Elvia</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project6\'>Truth</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project7\'>Kingdoms</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project8\'>Terminal World</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project9\'>Monster Office Workplace</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project10\'>Battle Princesses</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project11\'>Sacred Offerings</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project12\'>The Way</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project13\'>Conspiratorium</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project14\'>Conversion</a></br></br>'
	elif vKey == '2_5_1':
		vResult = '<a class=\'navlinkA\' href=\'/Section2/Section1/Index\'>Gynowars</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project2\'>Assault</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project3\'>Mars</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Section4/Index\'>Renley</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Section5/Index\'>Antarrea</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section5/Section1/Index\'>Global</a></br></br>'
		vResult += '		<a class=\'navlinkC\' href=\'/Section2/Section5/Section1/Project1\'>Team Tactial: Crash Ball</a></br></br>'
		vResult += '		<a class=\'navlinkC\' href=\'/Section2/Section5/Section1/Project2\'>Wars of Antarrea</a></br></br>'
		vResult += '		<a class=\'navlinkC\' href=\'/Section2/Section5/Section1/Project3\'>Revolutions: Invading Nations:</a></br></br>'
		vResult += '		<a class=\'navlinkC\' href=\'/Section2/Section5/Section1/Project4\'>Revolutions: Rebellion Against the Fist</a></br></br>'
		vResult += '		<a class=\'navlinkC\' href=\'/Section2/Section5/Section1/Project5\'>Revolutions: Return to Arms</a></br></br>'
		vResult += '		<a class=\'navlinkC\' href=\'/Section2/Section5/Section1/Project6\'>Revolutions: Post Wars</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section5/Section2/Index\'>Grendol</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section5/Section3/Index\'>Utopia</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section5/Section4/Index\'>Elvia</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project6\'>Truth</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project7\'>Kingdoms</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project8\'>Terminal World</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project9\'>Monster Office Workplace</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project10\'>Battle Princesses</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project11\'>Sacred Offerings</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project12\'>The Way</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project13\'>Conspiratorium</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project14\'>Conversion</a></br></br>'
	elif vKey == '2_5_2':
		vResult = '<a class=\'navlinkA\' href=\'/Section2/Section1/Index\'>Gynowars</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project2\'>Assault</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project3\'>Mars</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Section4/Index\'>Renley</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Section5/Index\'>Antarrea</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section5/Section1/Index\'>Global</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section5/Section2/Index\'>Grendol</a></br></br>'
		vResult += '		<a class=\'navlinkC\' href=\'/Section2/Section5/Section2/Project1\'>Land of the Orcish Empire: Age of Magic</a></br></br>'
		vResult += '		<a class=\'navlinkC\' href=\'/Section2/Section5/Section2/Project2\'>Coliseum: Arena</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section5/Section3/Index\'>Utopia</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section5/Section4/Index\'>Elvia</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project6\'>Truth</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project7\'>Kingdoms</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project8\'>Terminal World</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project9\'>Monster Office Workplace</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project10\'>Battle Princesses</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project11\'>Sacred Offerings</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project12\'>The Way</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project13\'>Conspiratorium</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project14\'>Conversion</a></br></br>'
	elif vKey == '2_5_3':
		vResult = '<a class=\'navlinkA\' href=\'/Section2/Section1/Index\'>Gynowars</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project2\'>Assault</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project3\'>Mars</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Section4/Index\'>Renley</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Section5/Index\'>Antarrea</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section5/Section1/Index\'>Global</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section5/Section2/Index\'>Grendol</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section5/Section3/Index\'>Utopia</a></br></br>'
		vResult += '		<a class=\'navlinkC\' href=\'/Section2/Section5/Section3/Project1\'>Avia:Elemental Angels</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section5/Section4/Index\'>Elvia</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project6\'>Truth</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project7\'>Kingdoms</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project8\'>Terminal World</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project9\'>Monster Office Workplace</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project10\'>Battle Princesses</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project11\'>Sacred Offerings</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project12\'>The Way</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project13\'>Conspiratorium</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project14\'>Conversion</a></br></br>'
	elif vKey == '2_5_4':
		vResult = '<a class=\'navlinkA\' href=\'/Section2/Section1/Index\'>Gynowars</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project2\'>Assault</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project3\'>Mars</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Section4/Index\'>Renley</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Section5/Index\'>Antarrea</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section5/Section1/Index\'>Global</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section5/Section2/Index\'>Grendol</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section5/Section3/Index\'>Utopia</a></br></br>'
		vResult += '	<a class=\'navlinkB\' href=\'/Section2/Section5/Section4/Index\'>Elvia</a></br></br>'
		vResult += '		<a class=\'navlinkC\' href=\'/Section2/Section5/Section4/Project1\'>Nine Card</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project6\'>Truth</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project7\'>Kingdoms</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project8\'>Terminal World</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project9\'>Monster Office Workplace</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project10\'>Battle Princesses</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project11\'>Sacred Offerings</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project12\'>The Way</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project13\'>Conspiratorium</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section2/Project14\'>Conversion</a></br></br>'
	elif vKey == '3':
		vResult = '<a class=\'navlinkA\' href=\'/Section3/Project1\'>Online Experience Downloads</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section3/Project2\'>Game Maker Downloads</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section3/Project3\'>Java Downloads</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section3/Project4\'>C# Downloads</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Section3/Project5\'>C++ Downloads</a></br></br>'
	else:
		vResult = '<a class=\'navlinkA\' href=\'/AboutUs\'>About Us</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Media\'>Media</a></br></br>'
		vResult += '<a class=\'navlinkA\' href=\'/Minecraft\'>Minecraft!</a></br></br>'
	return vResult

