def getVersions(vPage, vLevel):
	vKey = vLevel+'_'+vPage

	vResult = ''
	vDefault = ''
	
	vDefault += '<a href=\'http://htkb.dyndns.org/Index.html\'>HTML</a><br>'
	vDefault += '<a href=\'http://htkb.dyndns.org/Index.php\'>PHP</a><br>'
	vDefault += '<a href=\'http://htkb.dyndns.org/Index.shtml\'>Perl</a><br>'
	vDefault += '<a href=\'http://htkb.dyndns.org/SSI/Index.html\'>Apache SSI</a><br>'
	vDefault += '<a href=\'http://htkb.dyndns.org/Javascript/Index.html\'>HTML Javascript</a><br>'
	vDefault += '<a href=\'http://htkb.dyndns.org/JQuery/Index.html\'>JQuery</a><br>'
	vDefault += '<a href=\'http://htkb.dyndns.org/AngularJS/Index.html\'>Angular JS</a><br>'
	vDefault += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Index.xhtml\'>JSF</a><br>'
	vDefault += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Index.jsp\'>JSP</a><br>'
	vDefault += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Index.jsp\'>JSP Spring MVC</a><br>'
	vDefault += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Index.aspx\'>ASP.NET Javascript</a><br>'
	vDefault += '<a href=\'http://htkb.dyndns.org:81/ASP/Index.asp\'>ASP VBscript</a><br>'
	vDefault += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Index.cshtml\'>ASP.NET Web App</a><br>'
	vDefault += '<a href=\'http://htkb.dyndns.org:81/WebForm/Index.aspx\'>ASP.NET Webform</a><br>'
	vDefault += '<a href=\'http://htkb.dyndns.org:81/MVC/Main/Index\'>ASP.NET MVC App</a><br>'
	vDefault += '<a href=\'http://htkb.dyndns.org:83/Index\'>Ruby on Rails</a></br>'
	vDefault += '<a href=\'http://htkb.dyndns.org:84/Index\'>Node JS</a></br>'
	
	if vKey == '0_0':
		vResult += vDefault
	elif vKey == '0_1':
		vResult += '<a href=\'http://htkb.dyndns.org/AboutUs.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AboutUs.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AboutUs.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/AboutUs.html\'>Apache SSI</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/AboutUs.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/AboutUs.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/AboutUs.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/AboutUs.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/AboutUs.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/AboutUs.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/AboutUs.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/AboutUs.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/AboutUs.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/AboutUs.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Main/AboutUs\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/AboutUs\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/AboutUs\'>Node JS</a></br>'
	elif vKey == '0_2':
		vResult += '<a href=\'http://htkb.dyndns.org/Media.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Media.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Media.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Media.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Media.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Media.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Media.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Media.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Media.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Media.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Media.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Media.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Media.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Main/Media\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Media.html\'>Apache SSI</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Media\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Media\'>Node JS</a></br>'
	elif vKey == '0_3':
		vResult += '<a href=\'http://htkb.dyndns.org/Minecraft.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Minecraft.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Minecraft.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Minecraft.html\'>Apache SSI</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Minecraft.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Minecraft.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Minecraft.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Minecraft.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Minecraft.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Minecraft.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Minecraft.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Minecraft.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Minecraft.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Minecraft.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Main/Minecraft\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Minecraft\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Minecraft\'>Node JS</a></br>'
	elif vKey == '1_0':
		vResult += '<a href=\'http://htkb.dyndns.org/Division1/Index.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division1/Index.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division1/Index.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Division1/Index.html\'>Apache SSI</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Division1/Index.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Division1/Index.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Division1/Index.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Division1/Index.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Division1/Index.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Division1/Index.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Division1/Index.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Division1/Index.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Division1/Index.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Division1/Index.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Division1/Index\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Division1/Index\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Division1/Index\'>Node JS</a></br>'
	elif vKey == '1_1':
		vResult += '<a href=\'http://htkb.dyndns.org/Division1/Section1/Index.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division1/Section1/Index.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division1/Section1/Index.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Division1/Section1/Index.html\'>Apache SSI</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Division1/Section1/Index.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Division1/Section1/Index.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Division1/Section1/Index.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Division1/Section1/Index.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Division1/Section1/Index.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Division1/Section1/Index.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Division1/Section1/Index.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Division1/Section1/Index.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Division1/Section1/Index.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Division1/Section1/Index.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Division1_1/Index\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Division1/Section1/Index\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Division1/Section1/Index\'>Node JS</a></br>'
	elif vKey == '1_1_1':
		vResult += '<a href=\'http://htkb.dyndns.org/Division1/Section1/Project1.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division1/Section1/Project1.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division1/Section1/Project1.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Division1/Section1/Project1.html\'>Apache SSI</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Division1/Section1/Project1.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Division1/Section1/Project1.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Division1/Section1/Project1.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Division1/Section1/Project1.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Division1/Section1/Project1.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Division1/Section1/Project1.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Division1/Section1/Project1.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Division1/Section1/Project1.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Division1/Section1/Project1.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Division1/Section1/Project1.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Main/Division1_1/Project1\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Division1/Section1/Project1\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Division1/Section1/Project1\'>Node JS</a></br>'
	elif vKey == '1_1_2':
		vResult += '<a href=\'http://htkb.dyndns.org/Division1/Section1/Project2.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division1/Section1/Project2.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division1/Section1/Project2.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Division1/Section1/Project2.html\'>Apache SSI</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Division1/Section1/Project2.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Division1/Section1/Project2.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Division1/Section1/Project2.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Division1/Section1/Project2.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Division1/Section1/Project2.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Division1/Section1/Project2.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Division1/Section1/Project2.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Division1/Section1/Project2.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Division1/Section1/Project2.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Division1/Section1/Project2.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Main/Division1_1/Project2\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Division1/Section1/Project2\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Division1/Section1/Project2\'>Node JS</a></br>'
	elif vKey == '1_1_3':
		vResult += '<a href=\'http://htkb.dyndns.org/Division1/Section1/Project3.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division1/Section1/Project3.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division1/Section1/Project3.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Division1/Section1/Project3.html\'>Apache SSI</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Division1/Section1/Project3.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Division1/Section1/Project3.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Division1/Section1/Project3.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Division1/Section1/Project3.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Division1/Section1/Project3.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Division1/Section1/Project3.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Division1/Section1/Project3.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Division1/Section1/Project3.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Division1/Section1/Project3.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Division1/Section1/Project3.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Main/Division1_1/Project3\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Division1/Section1/Project3\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Division1/Section1/Project3\'>Node JS</a></br>'
	elif vKey == '1_1_4':
		vResult += '<a href=\'http://htkb.dyndns.org/Division1/Section1/Project4.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division1/Section1/Project4.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division1/Section1/Project4.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Division1/Section1/Project4.html\'>Apache SSI</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Division1/Section1/Project4.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Division1/Section1/Project4.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Division1/Section1/Project4.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Division1/Section1/Project4.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Division1/Section1/Project4.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Division1/Section1/Project4.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Division1/Section1/Project4.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Division1/Section1/Project4.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Division1/Section1/Project4.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Division1/Section1/Project4.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Division1_1/Project4\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Division1/Section1/Project4\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Division1/Section1/Project4\'>Node JS</a></br>'
	elif vKey == '1_1_5':
		vResult += '<a href=\'http://htkb.dyndns.org/Division1/Section1/Project4.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division1/Section1/Project4.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division1/Section1/Project4.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Division1/Section1/Project4.html\'>Apache SSI</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Division1/Section1/Project4.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Division1/Section1/Project4.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Division1/Section1/Project4.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Division1/Section1/Project4.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Division1/Section1/Project4.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Division1/Section1/Project4.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Division1/Section1/Project4.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Division1/Section1/Project4.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Division1/Section1/Project4.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Division1/Section1/Project4.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Division1_1/Project4\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Division1/Section1/Project4\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Division1/Section1/Project4\'>Node JS</a></br>'
	elif vKey == '2_0':
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Index.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Index.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Index.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Division2/Index.html\'>Apache SSI</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Division2/Index.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Division2/Index.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Division2/Index.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Division2/Index.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Division2/Index.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Division2/Index.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Division2/Index.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Division2/Index.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Division2/Index.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Division2/Index.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Main/Division2/Index\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Division2/Index\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Division2/Index\'>Node JS</a></br>'
	elif vKey == '2_2':
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Project2.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Project2.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Project2.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Division2/Project2.html\'>Apache SSI</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Division2/Project2.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Division2/Project2.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Division2/Project2.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Division2/Project2.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Division2/Project2.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Division2/Project2.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Division2/Project2.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Division2/Project2.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Division2/Project2.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Division2/Project2.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Main/Division2/Project2\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Division2/Project2\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Division2/Project2\'>Node JS</a></br>'
	elif vKey == '2_3':
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Project3.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Project3.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Project3.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Division2/Project3.html\'>Apache SSI</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Division2/Project3.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Division2/Project3.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Division2/Project3.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Division2/Project3.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Division2/Project3.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Division2/Project3.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Division2/Project3.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Division2/Project3.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Division2/Project3.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Division2/Project3.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Main/Division2/Project3\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Division2/Project3\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Division2/Project3\'>Node JS</a></br>'
	elif vKey == '2_6':
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Project6.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Project6.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Project6.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Division2/Project6.html\'>Apache SSI</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Division2/Project6.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Division2/Project6.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Division2/Project6.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Division2/Project6.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Division2/Project6.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Division2/Project6.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Division2/Project6.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Division2/Project6.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Division2/Project6.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Division2/Project6.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Main/Division2/Project6\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Division2/Project6\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Division2/Project6\'>Node JS</a></br>'
	elif vKey == '2_7':
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Project7.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Project7.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Project7.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Division2/Project7.html\'>Apache SSI</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Division2/Project7.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Division2/Project7.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Division2/Project7.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Division2/Project7.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Division2/Project7.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Division2/Project7.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Division2/Project7.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Division2/Project7.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Division2/Project7.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Division2/Project7.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Main/Division2/Project7\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Division2/Project7\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Division2/Project7\'>Node JS</a></br>'
	elif vKey == '2_8':
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Project8.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Project8.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Project8.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Division2/Project8.html\'>Apache SSI</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Division2/Project8.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Division2/Project8.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Division2/Project8.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Division2/Project8.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Division2/Project8.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Division2/Project8.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Division2/Project8.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Division2/Project8.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Division2/Project8.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Division2/Project8.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Main/Division2/Project8\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Division2/Project8\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Division2/Project8\'>Node JS</a></br>'
	elif vKey == '2_9':
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Project9.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Project9.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Project9.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Division2/Project9.html\'>Apache SSI</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Division2/Project9.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Division2/Project9.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Division2/Project9.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Division2/Project9.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Division2/Project9.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Division2/Project9.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Division2/Project9.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Division2/Project9.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Division2/Project9.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Division2/Project9.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Main/Division2/Project9\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Division2/Project9\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Division2/Project9\'>Node JS</a></br>'
	elif vKey == '2_10':
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Project10.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Project10.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Project10.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Division2/Project10.html\'>Apache SSI</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Division2/Project10.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Division2/Project10.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Division2/Project10.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Division2/Project10.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Division2/Project10.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Division2/Project10.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Division2/Project10.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Division2/Project10.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Division2/Project10.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Division2/Project10.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Main/Division2/Project10\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Division2/Project10\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Division2/Project10\'>Node JS</a></br>'
	elif vKey == '2_11':
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Project10.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Project10.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Project10.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Division2/Project10.html\'>Apache SSI</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Division2/Project10.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Division2/Project10.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Division2/Project10.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Division2/Project10.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Division2/Project10.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Division2/Project10.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Division2/Project10.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Division2/Project10.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Division2/Project10.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Division2/Project10.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Main/Division2/Project10\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Division2/Project10\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Division2/Project10\'>Node JS</a></br>'
	elif vKey == '2_12':
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Project12.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Project12.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Project12.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Division2/Project12.html\'>Apache SSI</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Division2/Project12.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Division2/Project12.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Division2/Project12.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Division2/Project12.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Division2/Project12.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Division2/Project12.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Division2/Project12.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Division2/Project12.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Division2/Project12.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Division2/Project12.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Main/Division2/Project12\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Division2/Project12\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Division2/Project12\'>Node JS</a></br>'
	elif vKey == '2_13':
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Project13.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Project13.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Project13.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Division2/Project13.html\'>Apache SSI</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Division2/Project13.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Division2/Project13.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Division2/Project13.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Division2/Project13.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Division2/Project13.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Division2/Project13.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Division2/Project13.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Division2/Project13.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Division2/Project13.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Division2/Project13.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Main/Division2/Project13\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Division2/Project13\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Division2/Project13\'>Node JS</a></br>'
	elif vKey == '2_14':
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Project14.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Project14.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Project14.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Division2/Project14.html\'>Apache SSI</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Division2/Project14.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Division2/Project14.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Division2/Project14.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Division2/Project14.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Division2/Project14.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Division2/Project14.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Division2/Project14.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Division2/Project14.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Division2/Project14.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Division2/Project14.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Main/Division2/Project14\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Division2/Project14\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Division2/Project14\'>Node JS</a></br>'
	elif vKey == '2_15':
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Project15.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Project15.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Project15.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Division2/Project15.html\'>Apache SSI</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Division2/Project15.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Division2/Project15.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Division2/Project15.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Division2/Project15.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Division2/Project15.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Division2/Project15.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Division2/Project15.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Division2/Project15.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Division2/Project15.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Division2/Project15.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Main/Division2/Project15\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Division2/Project15\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Division2/Project15\'>Node JS</a></br>'
	elif vKey == '2_16':
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Project16.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Project16.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Project16.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Division2/Project16.html\'>Apache SSI</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Division2/Project16.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Division2/Project16.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Division2/Project16.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Division2/Project16.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Division2/Project16.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Division2/Project16.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Division2/Project16.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Division2/Project16.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Division2/Project16.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Division2/Project16.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Main/Division2/Project16\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Division2/Project16\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Division2/Project16\'>Node JS</a></br>'
	elif vKey == '2_17':
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Project17.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Project17.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Project17.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Division2/Project17.html\'>Apache SSI</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Division2/Project17.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Division2/Project17.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Division2/Project17.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Division2/Project17.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Division2/Project17.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Division2/Project17.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Division2/Project17.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Division2/Project17.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Division2/Project17.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Division2/Project17.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Main/Division2/Project17\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Division2/Project17\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Division2/Project17\'>Node JS</a></br>'
	elif vKey == '2_1_0':
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section1/Project2.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section1/Project2.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section1/Project2.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Division2/Section1/Project2.html\'>Apache SSI</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Division2/Section1/Project2.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Division2/Section1/Project2.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Division2/Section1/Project2.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Division2/Section1/Project2.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Division2/Section1/Project2.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Division2/Section1/Project2.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Division2/Section1/Project2.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Division2/Section1/Project2.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Division2/Section1/Project2.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Division2/Section1/Project2.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Main/Division2/Section1/Project2\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Division2/Section1/Project2\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Division2/Section1/Project2\'>Node JS</a></br>'
	elif vKey == '2_1_1':
		vResult += '<a href=\'http://htkb.dyndns.org/Section1/Section6/Project1.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Section1/Section6/Project1.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Section1/Section6/Project1.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Section1/Section6/Project1.html\'>Apache SSI</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Division1/Section1/Project1.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Section1/Section6/Project1.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Section1/Section6/Project1.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Section1/Section6/Project1.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Section1/Section6/Project1.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Section1/Section6/Project1.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Section1/Section6/Project1.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Section1/Section6/Project1.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Section1/Section6/Project1.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Section1/Section6/Project1.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Main/Section1_6/Project1\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Section1/Section6/Project1\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Section1/Section6/Project1\'>Node JS</a></br>'
	elif vKey == '2_1_2':
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section1/Project2.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section1/Project2.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section1/Project2.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Division2/Section1/Project2.html\'>Apache SSI</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Division2/Section1/Project2.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Division2/Section1/Project2.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Division2/Section1/Project2.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Division2/Section1/Project2.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Division2/Section1/Project2.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Division2/Section1/Project2.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Division2/Section1/Project2.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Division2/Section1/Project2.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Division2/Section1/Project2.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Division2/Section1/Project2.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Main/Division2/Section1/Project2\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Division2/Section1/Project2\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Division2/Section1/Project2\'>Node JS</a></br>'
	elif vKey == '2_1_3':
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section1/Project3.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section1/Project3.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section1/Project3.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Division2/Section1/Project3.html\'>Apache SSI</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Division2/Section1/Project3.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Division2/Section1/Project3.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Division2/Section1/Project3.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Division2/Section1/Project3.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Division2/Section1/Project3.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Division2/Section1/Project3.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Division2/Section1/Project3.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Division2/Section1/Project3.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Division2/Section1/Project3.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Division2/Section1/Project3.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Main/Division2/Section1/Project3\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Division2/Section1/Project3\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Division2/Section1/Project3\'>Node JS</a></br>'
	elif vKey == '2_4_0':
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section4/Index.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section4/Index.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section4/Index.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Division2/Section4/Index.html\'>Apache SSI</a><br>'						  
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Division2/Section4/Index.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Division2/Section4/Index.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Division2/Section4/Index.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Division2/Section4/Index.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Division2/Section4/Index.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Division2/Section4/Index.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Division2/Section4/Index.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Division2/Section4/Index.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Division2/Section4/Index.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Division2/Section4/Index.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Main/Division2/Section4/Index\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Division2/Section4/Index\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Division2/Section4/Index\'>Node JS</a></br>'
	elif vKey == '2_4_1':
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section4/Project1.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section4/Project1.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section4/Project1.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Division2/Section4/Project1.html\'>Apache SSI</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Division2/Section4/Project1.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Division2/Section4/Project1.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Division2/Section4/Project1.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Division2/Section4/Project1.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Division2/Section4/Project1.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Division2/Section4/Project1.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Division2/Section4/Project1.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Division2/Section4/Project1.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Division2/Section4/Project1.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Division2/Section4/Project1.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Main/Division2/Section4/Project1\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Division2/Section4/Project1\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Division2/Section4/Project1\'>Node JS</a></br>'
	elif vKey == '2_4_2':
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section4/Project2.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section4/Project2.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section4/Project2.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Division2/Section4/Project2.html\'>Apache SSI</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Division2/Section4/Project2.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Division2/Section4/Project2.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Division2/Section4/Project2.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Division2/Section4/Project2.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Division2/Section4/Project2.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Division2/Section4/Project2.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Division2/Section4/Project2.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Division2/Section4/Project2.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Division2/Section4/Project2.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Division2/Section4/Project2.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Main/Division2/Section4/Project2\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Division2/Section4/Project2\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Division2/Section4/Project2\'>Node JS</a></br>'
	elif vKey == '2_5_0':
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section5/Index.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section5/Index.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section5/Index.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Division2/Section5/Index.html\'>Apache SSI</a><br>'	
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Division2/Section5/Index.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Division2/Section5/Index.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Division2/Section5/Index.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Division2/Section5/Index.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Division2/Section5/Index.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Division2/Section5/Index.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Division2/Section5/Index.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Division2/Section5/Index.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Division2/Section5/Index.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Division2/Section5/Index.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Main/Division2/Section5/Index\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Division2/Section5/Index\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Division2/Section5/Index\'>Node JS</a></br>'
	elif vKey == '2_5_1_0':
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section5/Section1/Index.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section5/Section1/Index.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section5/Section1/Index.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Division2/Section5/Section1/Index.html\'>Apache SSI</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Division2/Section5/Section1/Index.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Division2/Section5/Section1/Index.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Division2/Section5/Section1/Index.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Division2/Section5/Section1/Index.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Division2/Section5/Section1/Index.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Division2/Section5/Section1/Index.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Division2/Section5/Section1/Index.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Division2/Section5/Section1/Index.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Division2/Section5/Section1/Index.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Division2/Section5/Section1/Index.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Main/Division2/Section5/Section1/Index\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Division2/Section5/Section1/Index\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Division2/Section5/Section1/Index\'>Node JS</a></br>'
	elif vKey == '2_5_1_1':
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section5/Section1/Project1.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section5/Section1/Project1.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section5/Section1/Project1.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Division2/Section5/Section1/Project1.html\'>Apache SSI</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Division2/Section5/Section1/Project1.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Division2/Section5/Section1/Project1.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Division2/Section5/Section1/Project1.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Division2/Section5/Section1/Project1.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Division2/Section5/Section1/Project1.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Division2/Section5/Section1/Project1.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Division2/Section5/Section1/Project1.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Division2/Section5/Section1/Project1.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Division2/Section5/Section1/Project1.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Division2/Section5/Section1/Project1.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Main/Division2/Section5/Section1/Project1\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Division2/Section5/Section1/Project1\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Division2/Section5/Section1/Project1\'>Node JS</a></br>'
	elif vKey == '2_5_1_2':
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section5/Section1/Project2.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section5/Section1/Project2.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section5/Section1/Project2.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Division2/Section5/Section1/Project2.html\'>Apache SSI</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Division2/Section5/Section1/Project2.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Division2/Section5/Section1/Project2.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Division2/Section5/Section1/Project2.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Division2/Section5/Section1/Project2.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Division2/Section5/Section1/Project2.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Division2/Section5/Section1/Project2.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Division2/Section5/Section1/Project2.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Division2/Section5/Section1/Project2.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Division2/Section5/Section1/Project2.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Division2/Section5/Section1/Project2.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Main/Division2/Section5/Section1/Project2\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Division2/Section5/Section1/Project2\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Division2/Section5/Section1/Project2\'>Node JS</a></br>'
	elif vKey == '2_5_1_3':
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section5/Section1/Project3.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section5/Section1/Project3.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section5/Section1/Project3.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Division2/Section5/Section1/Project3.html\'>Apache SSI</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Division2/Section5/Section1/Project3.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Division2/Section5/Section1/Project3.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Division2/Section5/Section1/Project3.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Division2/Section5/Section1/Project3.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Division2/Section5/Section1/Project3.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Division2/Section5/Section1/Project3.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Division2/Section5/Section1/Project3.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Division2/Section5/Section1/Project3.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Division2/Section5/Section1/Project3.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Division2/Section5/Section1/Project3.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Main/Division2/Section5/Section1/Project3\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Division2/Section5/Section1/Project3\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Division2/Section5/Section1/Project3\'>Node JS</a></br>'
	elif vKey == '2_5_1_4':
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section5/Section1/Project4.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section5/Section1/Project4.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section5/Section1/Project4.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Division2/Section5/Section1/Project4.html\'>Apache SSI</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Division2/Section5/Section1/Project4.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Division2/Section5/Section1/Project4.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Division2/Section5/Section1/Project4.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Division2/Section5/Section1/Project4.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Division2/Section5/Section1/Project4.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Division2/Section5/Section1/Project4.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Division2/Section5/Section1/Project4.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Division2/Section5/Section1/Project4.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Division2/Section5/Section1/Project4.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Division2/Section5/Section1/Project4.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Main/Division2/Section5/Section1/Project4\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Division2/Section5/Section1/Project4\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Division2/Section5/Section1/Project4\'>Node JS</a></br>'
	elif vKey == '2_5_1_5':
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section5/Section1/Project5.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section5/Section1/Project5.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section5/Section1/Project5.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Division2/Section5/Section1/Project5.html\'>Apache SSI</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Division2/Section5/Section1/Project5.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Division2/Section5/Section1/Project5.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Division2/Section5/Section1/Project5.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Division2/Section5/Section1/Project5.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Division2/Section5/Section1/Project5.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Division2/Section5/Section1/Project5.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Division2/Section5/Section1/Project5.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Division2/Section5/Section1/Project5.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Division2/Section5/Section1/Project5.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Division2/Section5/Section1/Project5.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Main/Division2/Section5/Section1/Project5\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Division2/Section5/Section1/Project5\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Division2/Section5/Section1/Project5\'>Node JS</a></br>'
	elif vKey == '2_5_1_6':
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section5/Section1/Project6.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section5/Section1/Project6.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section5/Section1/Project6.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Division2/Section5/Section1/Project6.html\'>Apache SSI</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Division2/Section5/Section1/Project6.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Division2/Section5/Section1/Project6.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Division2/Section5/Section1/Project6.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Division2/Section5/Section1/Project6.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Division2/Section5/Section1/Project6.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Division2/Section5/Section1/Project6.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Division2/Section5/Section1/Project6.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Division2/Section5/Section1/Project6.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Division2/Section5/Section1/Project6.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Division2/Section5/Section1/Project6.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Main/Division2/Section5/Section1/Project6\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Division2/Section5/Section1/Project6\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Division2/Section5/Section1/Project6\'>Node JS</a></br>'
	elif vKey == '2_5_2_0':
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section5/Section2/Index.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section5/Section2/Index.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section5/Section2/Index.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Division2/Section5/Section2/Index.html\'>Apache SSI</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Division2/Section5/Section2/Index.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Division2/Section5/Section2/Index.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Division2/Section5/Section2/Index.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Division2/Section5/Section2/Index.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Division2/Section5/Section2/Index.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Division2/Section5/Section2/Index.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Division2/Section5/Section2/Index.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Division2/Section5/Section2/Index.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Division2/Section5/Section2/Index.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Division2/Section5/Section2/Index.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Main/Division2/Section5/Section2/Index\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Division2/Section5/Section2/Index\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Division2/Section5/Section2/Index\'>Node JS</a></br>'
	elif vKey == '2_5_2_1':
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section5/Section2/Project1.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section5/Section2/Project1.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section5/Section2/Project1.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Division2/Section5/Section2/Project1.html\'>Apache SSI</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Division2/Section5/Section2/Project1.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Division2/Section5/Section2/Project1.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Division2/Section5/Section2/Project1.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Division2/Section5/Section2/Project1.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Division2/Section5/Section2/Project1.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Division2/Section5/Section2/Project1.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Division2/Section5/Section2/Project1.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Division2/Section5/Section2/Project1.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Division2/Section5/Section2/Project1.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Division2/Section5/Section2/Project1.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Main/Division2/Section5/Section2/Project1\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Division2/Section5/Section2/Project1\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Division2/Section5/Section2/Project1\'>Node JS</a></br>'
	elif vKey == '2_5_2_2':
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section5/Section2/Project2.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section5/Section2/Project2.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section5/Section2/Project2.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Division2/Section5/Section2/Project2.html\'>Apache SSI</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Division2/Section5/Section2/Project2.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Division2/Section5/Section2/Project2.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Division2/Section5/Section2/Project2.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Division2/Section5/Section2/Project2.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Division2/Section5/Section2/Project2.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Division2/Section5/Section2/Project2.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Division2/Section5/Section2/Project2.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Division2/Section5/Section2/Project2.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Division2/Section5/Section2/Project2.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Division2/Section5/Section2/Project2.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Main/Division2/Section5/Section2/Project2\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Division2/Section5/Section2/Project2\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Division2/Section5/Section2/Project2\'>Node JS</a></br>'
	elif vKey == '2_5_3_0':
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section5/Section3/Index.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section5/Section3/Index.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section5/Section3/Index.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Division2/Section5/Section3/Index.html\'>Apache SSI</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Division2/Section5/Section3/Index.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Division2/Section5/Section3/Index.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Division2/Section5/Section3/Index.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Division2/Section5/Section3/Index.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Division2/Section5/Section3/Index.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Division2/Section5/Section3/Index.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Division2/Section5/Section3/Index.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Division2/Section5/Section3/Index.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Division2/Section5/Section3/Index.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Division2/Section5/Section3/Index.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Main/Division2/Section5/Section3/Index\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Division2/Section5/Section3/Index\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Division2/Section5/Section3/Index\'>Node JS</a></br>'
	elif vKey == '2_5_3_1':
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section5/Section4/Project1.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section5/Section4/Project1.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section5/Section4/Project1.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Division2/Section5/Section4/Project1.html\'>Apache SSI</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Division2/Section5/Section4/Project1.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Division2/Section5/Section4/Project1.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Division2/Section5/Section4/Project1.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Division2/Section5/Section4/Project1.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Division2/Section5/Section4/Project1.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Division2/Section5/Section4/Project1.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Division2/Section5/Section4/Project1.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Division2/Section5/Section4/Project1.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Division2/Section5/Section4/Project1.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Division2/Section5/Section4/Project1.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Main/Division2/Section5/Section4/Project1\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Division2/Section5/Section4/Project1\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Division2/Section5/Section4/Project1\'>Node JS</a></br>'
	elif vKey == '2_5_4_0':
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section5/Section4/Index.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section5/Section4/Index.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section5/Section4/Index.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Division2/Section5/Section4/Index.html\'>Apache SSI</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Division2/Section5/Section4/Index.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Division2/Section5/Section4/Index.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Division2/Section5/Section4/Index.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Division2/Section5/Section4/Index.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Division2/Section5/Section4/Index.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Division2/Section5/Section4/Index.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Division2/Section5/Section4/Index.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Division2/Section5/Section4/Index.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Division2/Section5/Section4/Index.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Division2/Section5/Section4/Index.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Main/Division2/Section5/Section4/Index\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Division2/Section5/Section4/Index\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Division2/Section5/Section4/Index\'>Node JS</a></br>'
	elif vKey == '2_5_4_1':
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section5/Section4/Project1.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section5/Section4/Project1.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division2/Section5/Section4/Project1.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Division2/Section5/Section4/Project1.html\'>Apache SSI</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Division2/Section5/Section4/Project1.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Division2/Section5/Section4/Project1.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Division2/Section5/Section4/Project1.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Division2/Section5/Section4/Project1.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Division2/Section5/Section4/Project1.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Division2/Section5/Section4/Project1.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Division2/Section5/Section4/Project1.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Division2/Section5/Section4/Project1.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Division2/Section5/Section4/Project1.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Division2/Section5/Section4/Project1.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Main/Division2/Section5/Section4/Project1\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Division2/Section5/Section4/Project1\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Division2/Section5/Section4/Project1\'>Node JS</a></br>'
	elif vKey == '3_0':
		vResult += '<a href=\'http://htkb.dyndns.org/Division3/Index.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division3/Index.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division3/Index.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Division3/Index.html\'>Apache SSI</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Division3/Index.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Division3/Index.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Division3/Index.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Division3/Index.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Division3/Index.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Division3/Index.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Division3/Index.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Division3/Index.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Division3/Index.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Division3/Index.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Main/Division3/Index\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Division3/Index\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Division3/Index\'>Node JS</a></br>'
	elif vKey == '3_1':
		vResult += '<a href=\'http://htkb.dyndns.org/Division3/Project1.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division3/Project1.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division3/Project1.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Division3/Project1.html\'>Apache SSI</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Division3/Project1.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Division3/Project1.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Division3/Project1.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Division3/Project1.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Division3/Project1.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Division3/Project1.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Division3/Project1.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Division3/Project1.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Division3/Project1.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Division3/Project1.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Main/Division3/Project1\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Division3/Project1\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Division3/Project1\'>Node JS</a></br>'
	elif vKey == '3_2':
		vResult += '<a href=\'http://htkb.dyndns.org/Division3/Project2.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division3/Project2.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division3/Project2.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Division3/Project2.html\'>Apache SSI</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Division3/Project2.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Division3/Project2.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Division3/Project2.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Division3/Project2.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Division3/Project2.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Division3/Project2.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Division3/Project2.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Division3/Project2.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Division3/Project2.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Division3/Project2.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Main/Division3/Project2\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Division3/Project2\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Division3/Project2\'>Node JS</a></br>'
	elif vKey == '3_3':
		vResult += '<a href=\'http://htkb.dyndns.org/Division3/Project3.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division3/Project3.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division3/Project3.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Division3/Project3.html\'>Apache SSI</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Division3/Project3.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Division3/Project3.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Division3/Project3.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Division3/Project3.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Division3/Project3.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Division3/Project3.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Division3/Project3.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Division3/Project3.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Division3/Project3.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Division3/Project3.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Main/Division3/Project3\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Division3/Project3\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Division3/Project3\'>Node JS</a></br>'
	elif vKey == '3_4':
		vResult += '<a href=\'http://htkb.dyndns.org/Division3/Project4.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division3/Project4.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division3/Project4.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Division3/Project4.html\'>Apache SSI</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Division3/Project4.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Division3/Project4.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Division3/Project4.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Division3/Project4.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Division3/Project4.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Division3/Project4.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Division3/Project4.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Division3/Project4.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Division3/Project4.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Division3/Project4.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Main/Division3/Project4\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Division3/Project4\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Division3/Project4\'>Node JS</a></br>'
	elif vKey == '3_5':
		vResult += '<a href=\'http://htkb.dyndns.org/Division3/Project5.html\'>HTML</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division3/Project5.php\'>PHP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Division3/Project5.shtml\'>Perl</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/SSI/Division3/Project5.html\'>Apache SSI</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/Javascript/Division3/Project5.html\'>HTML Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/JQuery/Division3/Project5.html\'>JQuery</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org/AngularJS/Division3/Project5.html\'>Angular JS</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSFApplication/Division3/Project5.xhtml\'>JSF</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/JSPApplication/Division3/Project5.jsp\'>JSP</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:8080/SpringMVC/Division3/Project5.jsp\'>JSP Spring MVC</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASPNET/Division3/Project5.aspx\'>ASP.NET Javascript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/ASP/Division3/Project5.asp\'>ASP VBscript</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebApplication/Division3/Project5.cshtml\'>ASP.NET Web App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/WebForm/Division3/Project5.aspx\'>ASP.NET Webform</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:81/MVC/Main/Division3/Project5\'>ASP.NET MVC App</a><br>'
		vResult += '<a href=\'http://htkb.dyndns.org:83/Division3/Project5\'>Ruby on Rails</a></br>'
		vResult += '<a href=\'http://htkb.dyndns.org:84/Division3/Project5\'>Node JS</a></br>'
	else:
		vResult = vDefault
	return vResult


