function WriteWebpage(vPage, vLevel, vExtension)
{
    Response.Write("<table id=\"idTableMain\">");
		Response.Write("<tr id=\"idHeaderRow\">");
            Response.Write("<td id=\"idHeaderRowCenter\" colspan=\"3\">");
                TitlePicture(vLevel);
			Response.Write("</td>");
        Response.Write("</tr>");
        Response.Write("<tr id=\"idNavigationRow\">");
            Response.Write("<td id=\"idNavigationBar\" colspan=\"3\">");
                NavBar(vLevel, vExtension);
            Response.Write("</td>");
        Response.Write("</tr>");    
        Response.Write("<tr id=\"idCenterRow\">");
			Response.Write("<td id=\"idCenterRowLeft\">");
				Response.Write("<h4>");
					Response.Write("Navigation");
				Response.Write("</h4>");
				Navigation(vLevel, vExtension);
			Response.Write("</td>");
			Response.Write("<td id=\"idCenterRowMain\">");
				Title(vPage);
				Header(vPage);
				Content(vPage);
			Response.Write("</td>");
			Response.Write("<td id=\"idCenterRowRight\">");
				Response.Write("<h4>");
					Response.Write("Information");
				Response.Write("</h4>");
				GetInformation(vExtension);
				Versions(vPage);
			Response.Write("</td>");
		Response.Write("</tr>");
        Response.Write("<tr id=\"idFooterRow\">");
			Response.Write("<td id=\"idFooterMain\" colspan=\"3\">");
				Response.Write("<p id=\"idFooterContent\">");
					Footer();
				Response.Write("</p>");
				Response.Write("<p id=\"idFooterManagement\">");
					WebMaster();
				Response.Write("</p>");
			Response.Write("</td>");
		Response.Write("</tr>");
    Response.Write("</table>");
}
